100-hours-a-week/15-Leafresh-BE

src/main/java/ktb/leafresh/backend/domain/auth/application/dto/OAuthUserInfoDto.java, src/main/java/ktb/leafresh/backend/domain/auth/application/factory/OAuthTokenFactory.java, src/main/java/ktb/leafresh/backend/domain/auth/application/service/jwt/JwtLogoutService.java, src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthLoginService.java, src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthSignupService.java, src/main/java/ktb/leafresh/backend/domain/auth/domain/entity/OAuth.java, src/main/java/ktb/leafresh/backend/domain/auth/domain/entity/enums/OAuthProvider.java, src/main/java/ktb/leafresh/backend/domain/auth/infrastructure/client/KakaoProfileClient.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthController.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthSignupController.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/dto/request/OAuthSignupRequestDto.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/dto/result/OAuthSignupResult.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/enums/LoginType.java, src/main/java/ktb/leafresh/backend/global/security/AuthCookieProvider.java, src/main/java/ktb/leafresh/backend/global/security/TokenProvider.java, src/main/resources/application-local.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
- 로그아웃 기능 구현
- `JwtLogoutService` 생성
- `OAuthLoginService`에 로그아웃 로직 추가
- `OAuthController`에 로그아웃 엔드포인트 구현
- 로그인/회원가입 구조 개선
- `OAuthProvider` enum 생성 및 도입
- `LoginType`은 로그인 방식(LOCAL/SOCIAL)으로, `OAuthProvider`는 실제 OAuth 플랫폼(KAKAO/GOOGLE/NAVER)으로 분리
- 기존 `LoginType` 기반 코드 전반 수정
- `OAuthSignupService` 및 `OAuthTokenFactory`에서 provider 처리 로직 수정
- `OAuthUserInfoDto`에 provider 필드 타입 변경
- DTO 및 유틸 정비
- `OAuthSignupResult` 생성 → 응답 데이터와 토큰 정보를 함께 전달
- `AuthCookieProvider` 내부 로직 리팩토링
- `TokenProvider` 중복 코드 제거 및 정리
- 환경 분리
- `application.yml` 분리 → `application-local.yml`, `application-prod.yml` 추가
---
- Close #18
- Close #19
---
- `develop` 브랜치에 직접 커밋한 변경사항을 본 브랜치(`feature/18-19-logout`)로 옮기기 위해 현재 커밋을 재정리 중입니다.
- 커밋 단위는 기능 중심으로 분리하여 올렸습니다.
=> [feat] 소셜 로그아웃 기능 구현 및 OAuthProvider 분리

src/main/java/ktb/leafresh/backend/global/TestController.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
- AI 서버와 통신 테스트를 위해 임시로 `SecurityConfig`에 허용 경로 추가
- `/spring/hello` (GET)
- `/spring/echo` (POST)
- `/spring/call-fastapi` (GET)
- `/spring/call-fastapi-post` (POST)
- `TestController` 작성
- FastAPI 서버에서 요청 받을 수 있도록 Spring → FastAPI, FastAPI → Spring 테스트 엔드포인트 구현
- 테스트 시 AI 서버 IP로 FastAPI 요청 URL 변경 가능하도록 처리
---
- AI 서버(Python FastAPI)와의 통신 연동을 개발 환경에서 빠르게 검증하기 위함
---
- 추후 운영 환경에서는 해당 테스트용 컨트롤러 및 보안 설정 제거 예정
- `SecurityConfig` 변경은 임시이므로 관련 로직이 있는 경우 충돌 주의
---
- Close #43
=> [feat] AI 서버 연동 테스트를 위한 임시 보안 설정 및 테스트 컨트롤러 추가

src/main/java/ktb/leafresh/backend/domain/auth/application/dto/OAuthUserInfoDto.java, src/main/java/ktb/leafresh/backend/domain/auth/infrastructure/client/KakaoProfileClient.java
OAuth 로그인 시 사용자 닉네임 정보를 저장할 수 있도록 `OAuthUserInfoDto`에 `nickname` 필드를 추가하였습니다.  
이에 따라 카카오 프로필 응답 파싱 및 DTO 생성 로직, 로그인 로그 출력부에 해당 필드를 반영하였습니다.
- `OAuthUserInfoDto` 클래스에 `nickname` 필드 추가
- `KakaoProfileClient`에서 nickname 파싱 및 전달
- `OAuthLoginService` 내 사용자 정보 로그에 nickname 출력 추가
- 기존 로그인/회원가입 흐름에는 영향 없음
- 추후 회원 가입 시 닉네임 기본값으로 사용 가능
=> feat: OAuthUserInfoDto에 nickname 필드 추가

src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthLoginService.java, src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthReissueTokenService.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthController.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
JWT 기반 인증 흐름에서 access token이 만료된 경우, refresh token을 이용해 access token을 재발급받을 수 있는 기능을 구현하였습니다.
- access token 만료 시 클라이언트가 refresh token을 함께 전송하도록 처리
- refresh token 유효성 검증 및 저장된 값과 일치 여부 검사
- 유효한 경우 새로운 access token 및 refresh token 발급 후 응답
- 유저 정보 기반 인증 객체(SecurityContext) 갱신
- access token 만료 후 refresh token으로 토큰 재발급 요청 → 정상 동작 확인
- refresh token 불일치 또는 만료 시 재발급 거부 → 예외 처리 정상 확인
- 토큰 응답 시 HttpOnly 쿠키에 access/refresh token 저장 방식 유지
=> feat: access token 만료 시 refresh token으로 재발급 로직 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/AiChallengePolicyValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/dto/AiChallengeValidationRequestDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeRepository.java
- `AiChallengePolicyValidator`에서 기존 챌린지 목록을 AI 서버에 전달하도록 기능 추가
- `GroupChallengeRepository`에 JPQL 기반의 `findAllValidAndOngoing(LocalDateTime)` 메서드 구현
- `AiChallengeValidationRequestDto`에 ChallengeSummary 리스트 필드 추가 및 활용
- AI 서버가 유사 챌린지 검증을 위해 기존 챌린지 정보를 필요로 함
- 유사 챌린지가 있을 경우 챌린지 생성을 제한하기 위한 정책 도입
- 그룹 챌린지 생성 API (`POST /api/challenges/group`)
- AI 서버와의 통신 로직 (`AiChallengeValidationClient`)
- 현재 시각 기준으로 `endDate >= now()`인 챌린지를 유효한 챌린지로 간주
- `LocalDate` → `LocalDateTime` 타입 일치 문제 해결 완료
=> feat: AI 챌린지 유사도 검증을 위한 현재 진행 중 챌린지 목록 조회 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeDetailResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeExampleImageDto.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/GroupChallengeVerificationRepository.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java, src/main/java/ktb/leafresh/backend/global/security/SecurityUtil.java
단체 챌린지 상세 조회 기능을 구현하고, 서비스 로직을 역할별로 분리하여 SRP(Single Responsibility Principle)를 적용하였습니다.  
비회원도 접근 가능한 API이며, 로그인 여부에 따라 인증 상태를 분기하여 응답합니다.
---
- `GET /api/challenges/group/{challengeId}` API 추가 (비로그인 사용자 접근 허용)
- 로그인된 경우 본인의 최신 인증 상태 조회 (성공/실패/대기/미제출)
- `GroupChallengeReadService`의 역할을 다음과 같이 분리
- `getChallengeOrThrow`: 챌린지 조회
- `getExampleImages`: 예시 이미지 DTO 변환
- `getVerificationImages`: 인증 이미지 리스트 조회
- `resolveChallengeStatus`: 인증 상태 결정
- `ChallengeStatus` Enum 응답값으로 직접 사용
- `SecurityConfig`: 해당 URI 비회원 접근 허용 설정
- `ErrorCode`: `CHALLENGE_NOT_FOUND` 상수 추가
- `GroupChallengeVerificationRepository`: 인증 상태 조회용 쿼리 메서드 추가
---
=> feat: 단체 챌린지 상세 조회 기능 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/GroupChallengeDomainValidator.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
- GroupChallengeDomainValidator 에 다음 유효성 검증 로직 추가:
- 인증 시작/종료 시간 간 10분 이상 차이
- 챌린지 시작일과 종료일 간 최소 1일 이상 차이
- 기존 종료일 < 시작일, 인증 종료 < 인증 시작 로직 유지
- ErrorCode에 관련 예외 코드 2종 추가
=> feat: 단체 챌린지 생성 시 기간 및 인증 시간 유효성 검증 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeUpdateService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/updater/GroupChallengeCategoryUpdater.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/updater/GroupChallengeExampleImageUpdater.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/updater/GroupChallengeUpdater.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/GroupChallengeDomainValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallenge.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallengeExampleImage.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeExampleImageRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeUpdateRequestDto.java, src/main/java/ktb/leafresh/backend/global/util/image/ImageEntity.java, src/main/java/ktb/leafresh/backend/global/util/image/ImageEntityUpdater.java
- GroupChallenge 수정 기능의 비즈니스 책임 분리
- GroupChallengeUpdateService → SRP에 맞춰 Updater 구성 요소로 책임 분할
- GroupChallengeUpdater: 작성자 검증 + 필드 업데이트
- GroupChallengeCategoryUpdater: 카테고리 검증 및 변경
- GroupChallengeExampleImageUpdater: 예시 이미지 유지/삭제/추가 처리
- ImageEntityUpdater 공통 유틸 적용
- soft delete, sequenceNumber 수정, saveAll 분기 처리
- GroupChallengeUpdateRequestDto에 Swagger 주석 및 유효성 검증 어노테이션 추가
- GroupChallengeExampleImage에 equals/hashCode 오버라이딩 및 getId(), updateSequenceNumber 구현 (ImageEntity 인터페이스 준수)
---
- 유지 이미지: `List<KeepImage(id, sequenceNumber)>` 처리
- 삭제 이미지: ID 리스트 기반 soft delete 처리
- 추가 이미지: 새 엔티티 생성 후 cascade or repository 저장
=> feat: 단체 챌린지 수정 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeDeleteService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeParticipantRecordRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
- 단체 챌린지 삭제 API (`DELETE /api/challenges/group/{challengeId}`) 구현
- 작성자 본인만 삭제 가능
- 참여자가 존재하는 경우 삭제 제한
- 이미 삭제된 챌린지 재삭제 방지
- `GroupChallengeDeleteService`에 삭제 비즈니스 로직 구현
- 삭제 전 유효성 검증: 존재 여부, 작성자 일치, 참여자 유무
- soft delete 적용 (`deletedAt` 설정)
- 예시 이미지 (`exampleImages`)도 함께 soft delete 처리
- `GroupChallengeParticipantRecordRepository`에 참여자 존재 여부 확인 메서드 추가
- `existsByGroupChallengeIdAndDeletedAtIsNull(challengeId)` 사용
- 삭제 성공 시 `deletedChallengeId`를 포함하는 JSON 응답 반환
- 실제 삭제가 아닌 soft delete 방식으로 처리되며, `deletedAt IS NULL` 조건으로 필터링된 쿼리를 사용하는 구조 전제
- 연관된 예시 이미지 soft delete 시점은 챌린지 soft delete 이후지만, 물리 삭제가 아니므로 무결성에 영향 없음
- 슬라이싱된 로그(`Slf4j`)로 삭제 흐름 디버깅 가능
=> feat: 단체 챌린지 삭제 API 구현 및 예시 이미지 동시 soft delete 처리

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/EventChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/EventChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/EventChallengeResponseDto.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
- `/api/challenges/events` GET API 생성
- 진행 중이며 삭제되지 않았고 종료되지 않은(event_flag = true) 챌린지만 조회
- `EventChallengeController`, `EventChallengeReadService`, `EventChallengeResponseDto` 새로 생성
- `GroupChallengeRepository`에 전용 조회 메서드(findOngoingEventChallenges) 추가
- SecurityConfig에 해당 URI를 허용 경로로 등록
=> feat: 이벤트 챌린지 목록 조회 API 구현Feature/29 all event challenge

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCategoryService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeCategoryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeCategoryController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeCategoryResponseDto.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
단체 챌린지 생성 시 사용할 수 있는 카테고리 목록 조회 API 추가
- `GroupChallengeCategoryController`, `GroupChallengeCategoryService`, `GroupChallengeCategoryResponseDto` 생성
- `GroupChallengeCategoryRepository`에 활성화된 카테고리를 순서대로 조회하는 메서드 (`findAllByActivatedIsTrueOrderBySequenceNumberAsc`) 추가
- 인증 없이 카테고리 목록을 조회할 수 있도록 `SecurityConfig`에 예외 URI 설정 추가
=> feat: 단체 챌린지 카테고리 목록 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeSummaryDto.java, src/main/java/ktb/leafresh/backend/global/config/QuerydslConfig.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/util/pagination/CursorPaginationHelper.java, src/main/java/ktb/leafresh/backend/global/util/pagination/CursorPaginationResult.java
- 단체 챌린지를 카테고리별로 조회하는 API를 구현하고,
- 커서 기반 페이지네이션 기능을 유틸리티로 추출해 적용했습니다.
- `/api/challenges/group/categories/{categoryId}` GET API 추가
- 커서 기반 페이지네이션 유틸리티(`CursorPaginationHelper`) 도입
- 마지막 커서를 추출하기 위한 id 추출 함수 적용
- `SecurityConfig`에 해당 경로를 비회원도 접근할 수 있도록 설정
- QueryDSL 기반 Repository (`GroupChallengeQueryRepository`) 생성
- 응답 DTO (`GroupChallengeSummaryDto`, `GroupChallengeListResponseDto`) 정의
- Postman으로 목록 조회 확인 완료
- 커서 기반 조회 및 hasNext 정상 동작 확인
=> feat: 카테고리 기반 단체 챌린지 목록 조회 API 및 커서 페이지네이션 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeVerificationListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeVerificationSummaryDto.java
단체 챌린지 상세 페이지에서 인증 내역을 무한 스크롤로 조회할 수 있도록, 인증 목록 조회 기능을 추가했습니다.
- Controller에 GET /{challengeId}/verifications 메서드 추가
- ReadService에 인증 내역 페이징 처리 로직 추가
- 인증 응답용 DTO (Summary/Response) 생성
- 인증 목록 조회 전용 QueryRepository 및 구현체 추가
=> feat: 단체 챌린지 인증 내역 목록 조회 기능 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCategoryService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeCategoryResponseDto.java
기존의 /api/challenges/group/categories/{categoryId} URI 방식 대신
쿼리 파라미터 방식으로 category 값을 받도록 변경했습니다.
- URI 기반 categoryId 조회 → query param 기반 category name 조회 방식으로 통일
- GroupChallengeController, GroupChallengeReadService에 category null validation 로직 추가
- GroupChallengeQueryRepository 및 구현체에 메서드명 및 파라미터 변경 (findByFilter)
- 카테고리 응답 DTO에서 id 제거 → name, label, imageUrl만 포함
=> feat: 단체 챌린지 목록 조회 시 category를 query param으로 받도록 리팩토링

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/enums/GroupChallengeCategoryName.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/init/GroupChallengeCategoryInitializer.java
1. `GroupChallengeCategoryName` ENUM 생성
- 한글 라벨, 이미지 URL, 시퀀스 번호 등 메타데이터 포함
- `toEnglish`, `getImageUrl`, `seeds()` 유틸 메서드 제공
2. `GroupChallengeCategoryInitializer` 리팩토링
- 기존 하드코딩된 시드 데이터를 ENUM 기반으로 대체
3. `GroupChallengeReadService`
- 한글 카테고리명을 ENUM name으로 변환하는 `resolveCategoryNameOrThrow` 메서드 추가
- 카테고리 기반 조회에서 사용
4. `SecurityConfig`
- `/api/challenges/group`  경로 permitAll로 명시
=> feat: 카테고리 기반 단체 챌린지 조회 기능 개발 및 관련 초기화 리팩토링

src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/factory/PersonalChallengeFactory.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeCreateService.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/validator/PersonalChallengeDomainValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/domain/entity/PersonalChallenge.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/infrastructure/repository/PersonalChallengeRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/controller/PersonalChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/request/PersonalChallengeCreateRequestDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/response/PersonalChallengeCreateResponseDto.java, src/main/java/ktb/leafresh/backend/global/common/entity/enums/DayOfWeek.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
- [기능] 운영자(admin) 전용 개인 챌린지 템플릿 생성 API 구현
- [도메인] 요일(DayOfWeek) 관리를 enum으로 전환하여 타입 안정성 강화
- [검증] 특정 요일에 최대 3개의 챌린지만 등록 가능하도록 유효성 로직 추가
- `DayOfWeek.java`: 글로벌 enum으로 요일 정의 (MONDAY~SUNDAY)
- `ErrorCode.java`: EXCEEDS_DAILY_PERSONAL_CHALLENGE_LIMIT 에러 코드 추가
- `PersonalChallenge.java`: `dayOfWeek` 타입을 `String` → `DayOfWeek` enum으로 변경
- `PersonalChallengeController`: POST /api/admin/challenges/personal 엔드포인트 추가
- `PersonalChallengeCreateRequestDto`: 요청 필드 정의
- `PersonalChallengeCreateService`: 생성 로직 및 도메인 유효성 검증 처리
- `PersonalChallengeDomainValidator`: 요일별 등록 개수 제한
- `PersonalChallengeFactory`: 도메인 객체 생성 책임 분리
- `PersonalChallengeRepository`: `countByDayOfWeek(DayOfWeek)` 쿼리 메서드 정의
=> feat: 운영자용 개인 챌린지 템플릿 생성 API 구현

src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/factory/PersonalChallengeExampleImageAssembler.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/factory/PersonalChallengeFactory.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeCreateService.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/validator/PersonalChallengeDomainValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/domain/entity/PersonalChallenge.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/domain/entity/PersonalChallengeExampleImage.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/controller/PersonalChallengeAdminController.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/request/PersonalChallengeCreateRequestDto.java
- 개인 챌린지 생성 요청 시 발생하던 NPE 및 leafReward 누락 오류 수정
- 정적 팩토리 패턴 적용 방식(GroupChallenge와 동일한 방식)으로 통일
- 예시 이미지 목록(exampleImages) 생성 시 addExampleImage 방식 적용
- leafReward 기본값 설정 (현재 30으로 고정)
- DTO 필드명 및 구조 재확인 (thumbnailImageUrl 등)
- 단체 챌린지 방식과의 구조 통일을 고려하여 정적 팩토리 내부에서 연관관계 설정 후, 명시적 `addExampleImage()` 호출로 양방향 유지
=> feat: 개인 챌린지 템플릿 생성 기능 개선 및 정적 팩토리 패턴 적용 방식 통일

src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/controller/PersonalChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/response/PersonalChallengeDetailResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/response/PersonalChallengeExampleImageDto.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/PersonalChallengeVerificationRepository.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
- 개인 챌린지 상세 정보를 조회하는 API를 개발했습니다.
- `SecurityConfig`: `/api/challenges/personal/{id}` URI 패턴을 인증 없이 접근 가능하도록 허용
- `ErrorCode`: PERSONAL_CHALLENGE_NOT_FOUND 에러 코드 추가
- `PersonalChallengeController`: GET /api/challenges/personal/{challengeId} 엔드포인트 추가
- `PersonalChallengeReadService`: 비회원 및 회원에 따른 인증 상태 로직 구현 포함
- `PersonalChallengeVerificationRepository`: 인증 상태 조회를 위한 findTopByMemberIdAndPersonalChallengeIdOrderByCreatedAtDesc 메서드 정의
- `PersonalChallengeDetailResponseDto`, `PersonalChallengeExampleImageDto`: 상세 응답 구조 정의
- 매주 요일별로 반복되는 개인 챌린지 구조에 맞춰 인증 제출 여부를 조회합니다.
=> feat: 개인 챌린지 상세 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/controller/PersonalChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/response/PersonalChallengeRuleResponseDto.java, src/main/java/ktb/leafresh/backend/global/config/JacksonTimeFormatConfig.java
- 개인 챌린지 인증 규약 조회 API 추가
- GET /api/challenges/personal/{challengeId}/rules
- 인증 시간 및 예시 이미지 목록을 조회 (회원/비회원 모두 접근 가능)
- Controller: getPersonalChallengeRules() 추가
- Service: getChallengeRules() 추가
- DTO: PersonalChallengeRuleResponseDto 생성
- LocalTime 직렬화 포맷 전역 통일
- "HH:mm:ss" → "HH:mm"
- JacksonTimeFormatConfig 등록을 통해 모든 LocalTime 필드에 일관된 포맷 적용
- 프론트 요청에 따라 초(`:ss`) 제거
=> feat: 개인 챌린지 인증 규약 조회 API 구현 및 LocalTime 응답 포맷 통일

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeExampleImageDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeRuleResponseDto.java
- 단체 챌린지 인증 규약 조회 기능을 구현했습니다.
- `GET /api/challenges/group/{challengeId}/rules` 엔드포인트 추가
- 인증 가능 기간 및 예시 이미지 목록 제공
- `GroupChallengeController`
- `getGroupChallengeRules(Long challengeId)` 메서드 추가
- `GroupChallengeReadService`
- 인증 규약을 반환하는 `getChallengeRules(Long challengeId)` 메서드 구현
- `GroupChallengeRuleResponseDto`
- 인증 가능 시작/종료 일자 및 시간 포함 응답 DTO 정의
- 예시 이미지 목록 포함
- Jackson 시간 포맷은 `HH:mm` 기준으로 출력됩니다.
- 단체 챌린지에 예시 이미지가 없는 경우 빈 배열로 반환됩니다.
=> feat: 단체 챌린지 인증 규약 조회 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeParticipationService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallenge.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallengeParticipantRecord.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/service/GroupChallengeParticipantManager.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/support/policy/GroupChallengePromotionPolicy.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/support/validator/GroupChallengeParticipationValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeParticipantRecordRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java, src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
단체 챌린지 참여 및 취소 기능을 DDD 원칙에 따라 도메인 계층 중심으로 구현하고, 참여/취소 및 대기자 승격 로직을 처리했습니다.
- `GroupChallengeParticipantManager`: 참여 및 취소 로직 처리
- `GroupChallengePromotionPolicy`: 대기자 중 가장 오래된 유저를 ACTIVE로 승격
- `GroupChallengeParticipationValidator`: 참여 중복/취소 불가 상태 검증
- `GroupChallengeParticipationService`: 도메인 서비스 위임
- `GroupChallengeController`: 참여/취소 API 연동
- `GroupChallenge`: `isFull()` 메서드 추가
- `GroupChallengeParticipantRecord`: `create()` 및 `isActive()` 메서드 추가
- `GroupChallengeParticipantRecordRepository`: 대기자 조회 쿼리 메서드 추가
- `ErrorCode`: 메시지 상수화 및 신규 에러 코드 등록
- 참여자 수는 ACTIVE 상태에서만 증가하며, 취소 시 대기자를 승격시킵니다.
- 하드코딩된 메시지는 `ErrorCode`로 이동하여 통일성을 확보했습니다.
=> feat: 단체 챌린지 참여/취소 기능 구현 및 도메인 분리

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationService.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/AiChatbotBaseInfoClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/AiChatbotFreeTextClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/FakeAiChatbotBaseInfoClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/FakeAiChatbotFreeTextClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotBaseInfoClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotFreeTextClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotBaseInfoRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotFreeTextRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/response/AiChatbotBaseInfoResponseDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/response/AiChatbotFreeTextResponseDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationController.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/request/ChatbotBaseInfoRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/request/ChatbotFreeTextRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/response/ChatbotBaseInfoResponseDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/response/ChatbotFreeTextResponseDto.java
사용자의 환경 관련 정보(선택 or 자유 입력)를 기반으로 AI 서버로부터 챌린지를 추천받는 챗봇 기능을 구현했습니다. 
- `ChatbotRecommendationController`: 사용자 선택 및 자유 입력 방식 요청 처리
- `ChatbotRecommendationService`: 입력 방식에 따른 AI 호출 및 응답 매핑 처리
- `ChatbotBaseInfoRequestDto`, `ChatbotFreeTextRequestDto`: 사용자 요청 DTO 정의
- `ChatbotBaseInfoResponseDto`, `ChatbotFreeTextResponseDto`: 사용자 응답 DTO 정의
- `AiChatbotBaseInfoClient`, `AiChatbotFreeTextClient`: AI 서버 통신 클라이언트 인터페이스 분리
- `HttpAiChatbotBaseInfoClient`, `HttpAiChatbotFreeTextClient`: 운영 환경용 WebClient 구현체
- `FakeAiChatbotBaseInfoClient`, `FakeAiChatbotFreeTextClient`: 로컬 테스트용 구현체
- `AiChatbotBaseInfoRequestDto`, `AiChatbotFreeTextRequestDto`: AI 요청 DTO
- `AiChatbotBaseInfoResponseDto`, `AiChatbotFreeTextResponseDto`: AI 응답 DTO
=> feat: 사용자 선택 및 자유 입력 기반 챗봇 추천 기능 구현

src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationController.java
@AuthenticationPrincipal에 CustomUserDetails 적용 및 기본 정보 요청 시 로그/예외 처리 추가
=> feat: 사용자 인증 객체로 CustomUserDetails 사용 및 로깅/예외 처리 추가

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/GroupChallengeVerification.java, src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/PersonalChallengeVerification.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/GroupChallengeVerificationRepository.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupChallengeVerificationController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/PersonalChallengeVerificationController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/util/ChallengeStatusMessageResolver.java, src/main/java/ktb/leafresh/backend/global/response/ApiResponse.java, src/main/java/ktb/leafresh/backend/global/util/polling/ChallengeVerificationPollingExecutor.java
- 개인/단체 챌린지 인증 결과를 클라이언트에서 롱폴링 방식으로 조회할 수 있도록 기능 추가
- 인증 상태에 따른 응답 메시지를 일관되게 전달하기 위한 처리 도입
- `ChallengeVerificationPollingExecutor`: 10초 동안 polling 후 상태 반환하는 유틸 클래스 추가
- `GroupChallengeVerificationResultQueryService`, `PersonalChallengeVerificationResultQueryService`: polling 유틸 적용
- `GroupChallengeVerificationController`, `PersonalChallengeVerificationController`: 인증 상태 메시지 처리 로직 반영
- `ChallengeStatusMessageResolver`: 인증 상태(enum)에 따른 사용자 메시지 분리
- `isFinalized()` 도메인 메서드 추가로 `PENDING_APPROVAL` 여부 판단 일관화
- 인증 결과 조회 API 요청 시 심사 중이면 최대 10초 동안 polling 후 결과 반환
- 인증을 제출하지 않은 경우 → `NOT_SUBMITTED`
- 심사 중인 경우 → `PENDING_APPROVAL`
- 심사 완료된 경우 → `SUCCESS` 또는 `FAILURE` 응답 확인
=> feat: 개인/단체 챌린지 인증 결과 롱폴링 조회 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/GroupChallengeMemberController.java
- 회원이 생성한 단체 챌린지 목록을 조회하는 API (`GET /api/members/challenges/group/creations`)를 추가했습니다.
- 커서 기반 페이지네이션 방식 적용 (기본 size=12, cursorId 사용)
- `GroupChallengeQueryRepository`에 QueryDSL 기반 쿼리 메서드 추가
- `GroupChallengeReadService`에서 로직 구현
- 컨트롤러에서는 `CustomUserDetails` 기반 인증 회원 ID 사용
=> feat: 회원이 생성한 단체 챌린지 목록 조회 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/client/HttpAiChallengeValidationClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotBaseInfoClient.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotFreeTextClient.java
빅뱅 배포 환경(Backend와 AI 서버가 동일 인스턴스에 공존)에서의 통신을 지원하기 위해 프로파일 및 설정을 수정하였습니다.
- `.env`에 `ai_server_base_url=http://localhost:8000` 설정 추가
- `application.yml`의 활성 프로파일을 `local` → `bigbang`으로 변경
- `ai-server.base-url: ${ai_server_base_url}` 구성
- WebClient가 AI 서버와 통신할 수 있도록 설정 정비
- `HttpAiChatbotBaseInfoClient`에 `@Qualifier("aiServerWebClient")` 주입 방식 적용
- `@RequiredArgsConstructor` 제거 후 명시적 생성자 작성
- `@Profile("!local")` 조건을 유지하고 있으므로, 운영 배포에서 자동으로 실제 서버 호출 로직이 활성화됨
- 로컬 테스트 시에는 `local` 프로파일을 사용하여 `FakeAiChatbotBaseInfoClient`로 대체 가능
=> chore: 빅뱅 배포 환경 대응을 위한 프로파일 및 AI 서버 연동 설정 추가

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationService.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotBaseInfoRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotFreeTextRequestDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationController.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
- 챗봇 추천 기능에서 인증 없이 사용 가능하도록 memberId 의존성을 제거했습니다.
- `ChatbotRecommendationController`: @AuthenticationPrincipal 제거
- `ChatbotRecommendationService`: memberId 제거 및 AI 요청 변경
- `AiChatbotBaseInfoRequestDto`: memberId 필드 제거
- `HttpAiChatbotBaseInfoClient`, `FakeAiChatbotBaseInfoClient`: 변경된 Dto 반영
=> refactor: 챗봇 API에서 인증 제거 및 memberId 파라미터 제거

src/main/java/ktb/leafresh/backend/domain/notification/application/service/NotificationCreateService.java, src/main/java/ktb/leafresh/backend/domain/notification/application/service/NotificationReadService.java, src/main/java/ktb/leafresh/backend/domain/notification/domain/entity/Notification.java, src/main/java/ktb/leafresh/backend/domain/notification/infrastructure/repository/NotificationReadQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/notification/infrastructure/repository/NotificationReadQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/notification/infrastructure/repository/NotificationRepository.java, src/main/java/ktb/leafresh/backend/domain/notification/presentation/controller/NotificationController.java, src/main/java/ktb/leafresh/backend/domain/notification/presentation/dto/response/NotificationDto.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveService.java
- 알림 도메인 관련 기능 추가
- 로그인된 유저의 알림 목록 조회 (커서 기반 페이징)
- 인증 결과 수신 시 알림 생성 기능
- 전체 알림 읽음 처리 API
- 알림 테이블 필드 확장
- challengeId, status 컬럼 추가
- SSE 미도입 상태 기준 전체 읽음 처리 방식
- 향후 SSE 도입 시 부분 업데이트 고려 필요
=> feat: 알림 조회 및 생성 기능 구현

src/main/resources/application.yml
- `application.yml` 내 GCP 설정 블록 제거
- `gcp.project-id`
- `gcp.credentials.location`
- `gcp.storage.bucket`
- 동일한 설정이 `application-bigbang.yml`에 포함되어 있어 중복 제거
- 공통 설정 파일에 불필요한 정보가 존재하지 않도록 정리하여 유지보수성 향상
=> chore: application.yml 내 GCP 설정 제거 (bigbang.yml에 포함됨)

src/main/java/ktb/leafresh/backend/domain/notification/application/service/NotificationCreateService.java, src/main/java/ktb/leafresh/backend/domain/notification/domain/entity/Notification.java, src/main/java/ktb/leafresh/backend/domain/notification/presentation/dto/response/NotificationDto.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveService.java
- 인증 결과 알림에 인증 사진 URL(imageUrl)을 포함할 수 있도록 전체 구조를 수정했습니다.
- Notification 엔티티에 imageUrl 컬럼을 추가하고, Dto 및 ReadService에 반영했습니다.
- Personal/GroupChallengeVerificationResultSaveService에서 imageUrl을 전달하도록 수정했습니다.
- NotificationCreateService는 새로운 imageUrl 파라미터를 받아 저장 시 포함되도록 개선했습니다.
=> feat: 알림에 인증 이미지(imageUrl) 포함 기능 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeSearchReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/enums/GroupChallengeCategoryName.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeManageController.java
- 단체 챌린지 목록 조회 시 `category` 파라미터를 더 이상 한글 label로 받지 않고, `GroupChallengeCategoryName` enum 값으로 직접 바인딩하도록 변경
- 이에 따라 기존의 `toEnglish()` 메서드 제거 및 서비스 계층 변환 로직도 함께 삭제
- Controller, Service에 모두 enum 기반 구조 반영
- 프론트에서도 category를 `"기타"` → `"ETC"` 형식으로 요청해야 하며, 잘못된 enum 값 전달 시 자동으로 400 Bad Request 처리됩니다.
=> refactor: 단체 챌린지 목록 조회 API category 파라미터 enum 방식으로 변경

.gitignore
- `.env.bigbang` 단일 파일을 `.env.bigbang-local`, `.env.bigbang-prod`로 환경별 분리
- 각 환경에 맞는 세팅을 명확히 분리하여 혼동 방지 및 협업 효율 향상
- `.gitignore`에 두 파일을 명시적으로 추가하여 git 추적 방지
- 여러 환경에서 동일 파일을 공유하면서 충돌/덮어쓰기 문제 발생
- 배포 스크립트에서 명확한 환경 구분을 위해 사전 정비
=> .env.bigbang 파일 환경별(local/prod)로 분리 및 .gitignore 업데이트

src/main/resources/application-local.yml
- samesite 값을 하드코딩된 'Lax'에서 환경변수 `${cookie_samesite}` 기반으로 변경 (유연한 설정 대응 목적)
- GCP 관련 설정 추가:
- project-id, credentials 경로, storage bucket 정보
- 향후 로컬에서도 GCS 연동 및 Presigned URL 기능 활용 가능하도록 구성
=> config: application-local.yml 환경변수 기반 쿠키 설정 및 GCP 설정 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallenge.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallengeParticipantRecord.java, src/main/java/ktb/leafresh/backend/domain/member/application/service/RewardGrantService.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/Member.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/GroupChallengeVerification.java, src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/PersonalChallengeVerification.java
- 개인 챌린지 및 단체 챌린지 인증 성공 시 나뭇잎 포인트 지급 로직 추가
- 인증 단건 성공 시 기본 보상 지급
- 챌린지 기간 내 전체 인증 완료 시 추가 보너스 지급
- 관련 엔티티 필드 및 메서드 수정:
- 인증 기록(Verification) 및 참가 기록(ParticipantRecord)에 보상 상태 업데이트
- 인증 성공/보상 지급 여부 판단을 위한 메서드 추가
- Member 엔티티에 리워드 지급 연동
=> feat: 개인/단체 챌린지 인증 보상 및 기간 완료 보너스 지급 로직 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCreatedReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeSearchReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeVerificationReadController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/CreatedGroupChallengeListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/CreatedGroupChallengeSummaryResponseDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeSummaryResponseDto.java, src/main/java/ktb/leafresh/backend/domain/notification/application/service/NotificationReadService.java, src/main/java/ktb/leafresh/backend/domain/notification/presentation/dto/response/NotificationListResponse.java, src/main/java/ktb/leafresh/backend/domain/notification/presentation/dto/response/NotificationSummaryResponse.java
- 커서 기반 페이지네이션 공통 구조의 items 키를 도메인별 명확한 네이밍으로 변경:
- 단체 챌린지 목록: `groupChallenges`
- 생성한 단체 챌린지 목록: `groupChallenges`
- 알림 목록: `notifications`
- 도메인별 응답 DTO 클래스 분리 및 적용
- Controller 및 Service 코드에서 새로운 DTO 구조에 맞게 전체 적용
- 응답 일관성 향상 및 프론트엔드 연동 편의성 개선
=> refactor: 커서 기반 페이지네이션 응답 도메인별 네이밍 적용 및 DTO 구조 개선

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/EventChallengeReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeRepository.java
- 이벤트 챌린지 조회 시점 기준으로 현재 ~ 2주 후까지 시작하는 챌린지만 조회되도록 필터링 로직 추가
- EventChallengeReadService 내부 비즈니스 로직 수정
=> feat: 이벤트 챌린지 조회 시 현재부터 2주 후까지로 필터링 적용

src/main/java/ktb/leafresh/backend/domain/verification/domain/support/validator/VerificationSubmitValidator.java
- VerificationSubmitValidator 클래스 생성
- content 값이 비어있거나 공백만 있는 경우 예외 발생 (`CONTENT_REQUIRED`)
- StringUtils.hasText() 기반의 텍스트 존재 여부 검증
- 도메인 유효성 검증 책임을 Validator 클래스로 분리하여 재사용성 및 테스트 용이성 향상
- `@Component` 등록을 통해 서비스 계층에서 주입 및 사용 가능
=> feat: 인증 제출 시 내용 필수 입력값 검증 Validator 추가

src/main/java/ktb/leafresh/backend/domain/auth/infrastructure/client/OAuthKakaoService.java
- 기존: 소셜 로그인 시 카카오로부터 프로필 이미지 URL 수신 후 저장
- 변경: 카카오 이미지 사용 대신 서비스 자체 디폴트 이미지 URL로 고정 설정
- 디폴트 이미지 URL: https://storage.googleapis.com/leafresh-images/init/user_icon.png
- 신규 가입자에 대해 일관된 초기 프로필 이미지 제공
=> refactor: 회원가입 시 카카오 프로필 이미지 대신 디폴트 이미지 설정

src/main/java/ktb/leafresh/backend/BackendApplication.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/EventChallengeInitService.java, src/main/java/ktb/leafresh/backend/global/scheduler/EventChallengeScheduler.java
- 매년 1월 1일 00시 정각에 **이벤트 챌린지를 자동 등록**하는 스케줄링 로직 구현
- 앱 시작 시 한 번 실행되도록 `ApplicationReadyEvent` 리스너도 추가
- `@EnableScheduling` 추가 (BackendApplication)
- `EventChallengeScheduler` 클래스 생성
- `@Scheduled(cron = "0 0 0 1 1 *")` 설정
- `@EventListener(ApplicationReadyEvent.class)` 설정
- `EventChallengeInitService` 생성
- `ETC` 카테고리, `admin` 계정, 기본 트리 레벨 존재 여부 검증 및 자동 생성
- 챌린지 시드 기반으로 연도별 제목 생성 후 중복 확인 및 등록
- GCS 프로필 이미지 URL 적용
- 단체 챌린지 초기 카테고리, 운영자 계정 생성 로직 포함
- 향후 다양한 이벤트 챌린지 자동화 기반 확장 가능
=> feat: 이벤트 챌린지 초기 등록 로직 및 스케줄러 추가

src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/FakeAiVerificationClient.java
- `@Profile("local")` 조건에 따라 활성화되는 FakeAiVerificationClient 구현
- 실제 AI 서버와 통신하지 않고 로그 출력으로 검증 요청을 대체
- 개발 및 테스트 시 AI 의존성 제거로 속도 및 안정성 향상
- `AiVerificationClient` 인터페이스를 구현하여 실제 구현체 대체 가능
=> test: 로컬 환경용 Fake AI 이미지 검증 클라이언트 추가

src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthSignupController.java, src/main/java/ktb/leafresh/backend/global/config/JwtSecurityConfig.java, src/main/java/ktb/leafresh/backend/global/security/AuthCookieProvider.java
- AuthCookieProvider 개선
- 쿠키 secure, sameSite 속성을 @Value를 통해 환경변수로 외부화
- @PostConstruct에서 설정 값 로그로 출력 (디버깅 용이)
- ResponseCookie 빌더 메서드로 쿠키 생성 통일
- JwtSecurityConfig 수정
- AuthCookieProvider 주입 추가 → 추후 JWT 관련 쿠키 설정에 활용 가능성 열어둠
- OAuthSignupController 수정
- 회원가입 시 AuthCookieProvider 주입 기반 쿠키 설정 가능하도록 필드 추가
- (이 PR에서는 직접 사용되진 않지만, 구조 반영됨)
=> refactor: 쿠키 설정 외부화 및 인증 응답 쿠키 생성 로직 개선

src/main/java/ktb/leafresh/backend/domain/verification/application/listener/VerificationEventListener.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/HttpAiVerificationClient.java
- AI 서버에서 202 Accepted 응답 시 result 파싱을 생략하고 콜백을 기다리도록 처리
- result 필드가 null인 경우 로그만 출력하고 예외는 발생시키지 않음
- VerificationEventListener 내에서 예외 발생 시 catch로 처리해 전체 비동기 흐름이 중단되지 않도록 방지
- 일부 요청에서 AI 응답을 잘 받았음에도 인증 상태가 계속 PENDING_APPROVAL에 머무는 이슈 발생
- 비동기 이벤트 흐름에서 예외 전파로 인해 예상치 못한 중단이 생기는 것을 방지
- 향후 AI 서버 콜백이 제대로 오지 않을 경우 재시도 메커니즘도 고려할 예정입니다.
=> fix: AI 인증 요청 응답 처리 개선 및 예외 대응

src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberUpdateService.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/Member.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/request/MemberUpdateRequestDto.java, src/main/java/ktb/leafresh/backend/global/exception/GlobalErrorCode.java, src/main/java/ktb/leafresh/backend/global/exception/MemberErrorCode.java
- 회원 닉네임 및 프로필 이미지 URL을 수정하는 API(PATCH /api/members) 구현
- 닉네임은 1~20자, 특수문자 제외 형식 검증 및 중복 확인 포함
- 이미지 URL은 GCS에서 발급된 주소만 허용
- Member 엔티티에 updateNickname, updateImageUrl 메서드 추가
- 변경 사항이 없을 경우 400 예외 처리 (NO_CONTENT)
- 예외 상황에 맞는 커스텀 예외 코드 추가
| 상황 | 응답 코드 | 메시지 |
|------|-----------|--------|
| 수정 성공 | 204 No Content | 회원 정보가 성공적으로 수정되었습니다. |
| 변경사항 없음 | 400 Bad Request | 변경된 정보가 없습니다. |
| 닉네임 중복 | 409 Conflict | 이미 사용 중인 닉네임입니다. |
=> feat: 회원 정보 수정 API 구현

src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberInfoQueryService.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/MemberInfoResponseDto.java, src/main/java/ktb/leafresh/backend/global/exception/MemberErrorCode.java
- `/api/members` GET API 구현
- 인증된 사용자의 닉네임, 트리 레벨 정보 반환
- 에러 응답 (401/403/404/500 등) 및 예외 핸들러 연동
- Controller/Service 로그 중복 제거 및 정리
=> feat: 회원 정보 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberUpdateService.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberRepository.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberController.java, src/main/java/ktb/leafresh/backend/global/exception/MemberErrorCode.java
- 본인 닉네임은 허용하되, 다른 사용자의 닉네임으로 변경을 시도할 경우 중복 예외가 발생하도록 로직 수정
- `existsByNicknameAndIdNot()` 사용으로 중복 조건을 명확하게 처리
- 변경사항 없는 경우 400 에러 반환되도록 예외 정의 (`NO_CHANGES`)
- 관련 예외 메시지 및 상태 코드 (`409`, `400`) 명확하게 설정
=> fix: 회원정보 수정 시 본인 외 사용자와 닉네임 중복되지 않도록 검사 로직 보완

src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberLeafPointReadService.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberLeafPointController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/MemberLeafPointResponseDto.java
- 로그인한 사용자의 currentLeafPoints를 반환하는 조회 API 구현
- MemberLeafPointController, Service, ResponseDto 생성
- 인증 필요 (401), 회원 없음 (404), 서버 오류 (500) 처리 포함
- 스웨거 명세 및 로그 포함
=> feat: 나뭇잎 보유량 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/member/domain/entity/Badge.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/enums/BadgeType.java
Badge 엔티티 및 BadgeType Enum을 추가
- Badge 엔티티 클래스 정의
- id, type, name, condition, imageUrl 필드 포함
- DB 컬럼명 매핑 처리 (`condition` → `acquisition_condition`)
- BadgeType Enum 추가 (GROUP, PERSONAL, TOTAL, SPECIAL, EVENT)
=> feat: 뱃지 엔티티 클래스 및 타입 정의 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/GroupChallengeDomainValidator.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeCreateRequestDto.java, src/main/java/ktb/leafresh/backend/global/exception/ChallengeErrorCode.java
- GroupChallengeCreateRequestDto에 `@NotNull` 메시지 커스터마이징
- ChallengeErrorCode에 `GROUP_CHALLENGE_REQUIRES_SUCCESS_IMAGE` 추가
- DomainValidator에서 성공 이미지만 필수로 검증하도록 로직 변경
- 수정 시 기존 성공 이미지 유지 여부 + 신규 이미지 조합 기준으로 판단
- 실패 이미지만 있는 경우 → 400 에러
- 성공 이미지가 1개 이상 포함된 경우 → 정상 생성
- exampleImages가 null인 경우 → `@NotNull` 유효성 검증 에러 발생
=> feat: 단체 챌린지 생성/수정 시 성공 예시 이미지 1개 이상 필수 조건 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeUpdateRequestDto.java
- GroupChallengeUpdateRequestDto.ExampleImages 내부 필드인 keep, newImages, deleted에
@JsonSetter(nulls = Nulls.AS_EMPTY) 적용
- 프론트엔드에서 null로 전송한 경우에도 빈 리스트로 처리되도록 하여 NPE 방지
- validation 및 stream 연산 안정성 확보
=> feat: 단체 챌린지 수정 시 예시 이미지 필드에 @JsonSetter(nulls = AS_EMPTY) 적용

src/main/java/ktb/leafresh/backend/global/initializer/TreeLevelInitializer.java
- TreeLevel 각 단계의 최소 leaf point 기준을 정책 변경에 따라 수정
- Google Cloud Storage의 대문자 enum 기반 이미지 URL 경로 적용
- 각 단계의 description 텍스트 가독성 및 표현 개선
=> refactor: TreeLevelInitializer 점수 기준, 이미지 URL 변경

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCategoryService.java, src/main/java/ktb/leafresh/backend/global/initializer/TreeLevelInitializer.java
- 'UPCYCLING' 라벨을 '업사이클링'으로 수정
- 'MEDIA' 라벨을 '문화 공유'로 수정
- 그룹 챌린지 카테고리 조회 시 ETC 카테고리는 제외하도록 필터링 추가
=> chore: 단체 챌린지 카테고리 라벨 수정 및 ETC 카테고리 제외

src/main/java/ktb/leafresh/backend/domain/member/application/service/RecentBadgeReadService.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/MemberBadge.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/enums/BadgeType.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberBadgeQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberBadgeQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberBadgeRepository.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberBadgeController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/BadgeSummaryDto.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/RecentBadgeListResponseDto.java, src/main/java/ktb/leafresh/backend/global/exception/MemberErrorCode.java
- 마이페이지에서 사용자의 최근 획득 뱃지를 최신순으로 조회하는 API 구현
- 기본 8개, count 파라미터로 개수 조절 가능
- MemberBadge 엔티티에 acquiredAt 필드 추가
- MemberBadgeQueryRepository + QueryDSL 구현
- BadgeSummaryDto → 공통 요약 응답으로 네이밍 변경
- ApiResponse 데이터 구조를 { badges: [] } 형태로 감쌈
- close #207 (마이페이지 - 최근 획득 뱃지 조회)
=> feat: 최근 획득한 뱃지 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/member/application/service/ProfileCardReadService.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/TreeLevelRepository.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/ProfileCardController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/ProfileCardResponseDto.java, src/main/java/ktb/leafresh/backend/global/exception/MemberErrorCode.java
- `/api/members/profilecard` GET API 구현
- 트리 레벨/인증 횟수/뱃지 목록 포함된 프로필 카드 응답 반환
- 다음 레벨 정보가 없을 경우 null 처리
- 최근 획득 뱃지 3개 조회 기능 연동
- 인증 실패, 권한 없음, 사용자 정보 없음, 서버 오류 케이스에 대한 에러 메시지 상수화 및 통일
=> feat: 프로필 카드 조회 API 구현 및 예외 응답 구조 정리

src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeUpdateRequestDto.java
- JSON에서 `"new"` 키로 전달되던 인증 예시 이미지 리스트가 DTO의 `newImages` 필드에 매핑되지 않는 문제를 해결했습니다.
- `@JsonProperty("new")` 어노테이션을 적용하여 Jackson 매핑 오류를 제거했습니다.
- 단체 챌린지 수정 API (PATCH /api/challenges/group/{id})
- 기존 트랜잭션 처리 및 도메인 로직은 변경 없이 그대로 유지됩니다.
- 프론트에서 `"new"` 키로 전송된 이미지들이 정상적으로 매핑되는지 확인 완료
=> fix: exampleImages.new 매핑 오류 수정

src/main/java/ktb/leafresh/backend/domain/member/application/service/LeafPointReadService.java, src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberLeafPointRewardService.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberLeafPointQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/MemberLeafPointQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/LeafPointController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/TotalLeafPointResponseDto.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/exception/LeafPointErrorCode.java, src/main/java/ktb/leafresh/backend/global/initializer/LeafPointInitializer.java
- `/api/leaves/count` 엔드포인트를 통한 누적 나뭇잎 수 조회 기능 구현
- Redis 캐시(`leafresh:totalLeafPoints:sum`) 기반 조회 + DB fallback 적용
- 애플리케이션 시작 시 Redis 초기화 로직 (`@PostConstruct`)
- MemberLeafPointRewardService를 통한 addLeafPoints() → Redis 동기화 반영
- TTL 없이 캐시 유지 (누적값은 영구 유지 목적)
- Redis 장애 시 DB fallback 및 로그 처리
- 모든 포인트 지급은 addLeafPoints() 기반으로 일관성 확보됨
=> feat: 누적 나뭇잎 수 조회 API + Redis 캐시 및 초기화 로직 구현

src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/client/HttpFeedbackAiClient.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/VerificationResultProcessor.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/AiVerificationSseClient.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/FakeAiVerificationSseClient.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/HttpAiVerificationSseClient.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/stream/AiVerificationStreamDispatcher.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupChallengeVerificationSubmitSseController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/PersonalChallengeVerificationSubmitSseController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/VerificationResultSseController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/response/VerificationSsePayload.java, src/main/java/ktb/leafresh/backend/global/exception/GlobalErrorCode.java, src/main/java/ktb/leafresh/backend/global/util/stream/SseStreamExecutor.java
이 PR은 AI 서버로부터 인증 결과를 SSE 기반으로 스트리밍하여 BE → FE로 전송하는 기능을 도입합니다 (AI → BE → FE)
- AI → BE
- `AiVerificationSseClient` 인터페이스를 정의하고, `Fake` / `Http` 구현체를 추가하였습니다.
- WebClient를 통해 AI 서버의 인증 SSE 스트림에 구독하도록 구성했습니다.
- BE 내부
- `AiVerificationStreamDispatcher`가 AI 서버에서 수신한 이벤트를 처리하고, 사용자별 sink로 결과를 전송합니다.
- `VerificationResultProcessor`를 통해 인증 상태 갱신 및 리워드 지급을 수행합니다.
- BE → FE
- 프론트엔드가 `/verification/result/stream` 경로를 통해 인증 결과를 구독할 수 있도록 SSE 전용 엔드포인트를 추가했습니다.
- `verificationId`는 URI가 아닌 SSE 이벤트의 본문(payload)에 포함되어 전송됩니다.
- 로컬 환경에서는 `FakeAiVerificationSseClient`를 사용하여 실제 SSE 연결을 방지합니다.
=> feat: AI → BE → FE 인증 결과 SSE 스트리밍 구조 구현

src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthLoginService.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthController.java, src/main/java/ktb/leafresh/backend/domain/auth/presentation/controller/OAuthSignupController.java, src/main/java/ktb/leafresh/backend/global/security/AuthCookieProvider.java
- 기존에는 accessTokenExpiresIn 값이 timestamp(ms)로 전달되어 Duration 계산이 잘못되었음
- Duration.ofMillis() 사용 시 절대 시간값이 들어가면서 만료일이 수년 뒤로 설정됨
- Duration.ofMinutes(30)으로 명확히 고정하여 30분 만료로 정확히 동작하도록 수정
- 메서드 시그니처 변경에 따라 호출부 전체 반영
=> fix: accessToken 쿠키 만료 시간이 잘못 설정되던 문제 수정 (30분으로 재설정)

src/main/java/ktb/leafresh/backend/domain/member/application/service/BadgeReadService.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberBadgeController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/BadgeListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/BadgeResponseDto.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/BadgeGrantManagerTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/BadgeReadServiceTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/policy/EventChallengeBadgePolicyTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/policy/GroupChallengeCategoryBadgePolicyTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/policy/PersonalChallengeStreakBadgePolicyTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/policy/SpecialBadgePolicyTest.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/policy/TotalVerificationCountBadgePolicyTest.java, src/test/java/ktb/leafresh/backend/support/fixture/BadgeFixture.java, src/test/java/ktb/leafresh/backend/support/fixture/MemberFixture.java
뱃지 목록을 조회하는 API를 구현하고, `BadgeFixture` 구조 변경에 따라 관련 테스트 코드를 전면 수정하였습니다.
1. 뱃지 목록 조회 API 기능 추가
- `BadgeReadService`, `BadgeListResponseDto`, `BadgeResponseDto` 구현
- 획득/미획득 상태 구분하여 응답하는 구조 설계 (`isLocked` 포함)
- `BadgeType` 기준으로 그룹화된 응답 형태 적용 (`group`, `personal`, `total`, `special`, `event`)
2. BadgeFixture 구조 변경
- `BadgeFixture.of(id, name, type)` 형태로 개선
- `getConditionByType()` 로 테스트 설명 문구 자동 생성
3. 테스트 전면 수정
- 모든 뱃지 관련 테스트 코드에서 기존 `BadgeFixture.of(name)` 사용 → `of(id, name, type)` 방식으로 일괄 변경
- 테스트 클래스 7개 이상 수정 (`BadgeReadServiceTest`, `SpecialBadgePolicyTest`, `TotalVerificationCountBadgePolicyTest` 등)
- 중복 제거, 가독성 개선, 의미 있는 테스트 ID 부여
=> feat: 뱃지 목록 조회 API 구현 및 테스트 일괄 수정

src/main/java/ktb/leafresh/backend/domain/feedback/application/listener/FeedbackResultEventListener.java, src/main/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackResultService.java, src/main/java/ktb/leafresh/backend/domain/feedback/presentation/controller/FeedbackResultController.java, src/main/java/ktb/leafresh/backend/domain/feedback/presentation/dto/request/FeedbackResultRequestDto.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/util/polling/FeedbackPollingExecutor.java
AI 서버로부터 수신한 주간 피드백을 저장하고, 사용자 마이페이지에서 이를 확인할 수 있도록 하는 기능을 구현했습니다. 주차 기준 중복 저장을 방지하며, 롱폴링 방식으로 결과를 조회할 수 있습니다.
- 피드백 저장 흐름:
- AI → BE로 전송된 피드백 결과 저장
- 동일 주차 중복 저장 방지 (member_id + week_monday 기준 existsBy 쿼리)
- 저장 완료 후 `FeedbackCreatedEvent` 발행
- 피드백 조회 기능:
- 로그인 사용자 기준, 현재 주차에 해당하는 피드백 결과 롱폴링 방식 조회
- 주간 피드백이 존재할 경우, 결과 content 반환
- 응답 Dto 및 polling executor 작성
=> feat: AI 서버로부터 수신한 주간 피드백 저장 및 조회 기능 구현

src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupChallengeVerificationSubmitController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/PersonalChallengeVerificationSubmitController.java
컨트롤러에서 `userDetails == null`일 때 `ResponseEntity`로 직접 응답을 내려주던 방식에서,
전역 예외 처리 로직을 따르도록 `CustomException(GlobalErrorCode.UNAUTHORIZED)`를 던지는 방식으로 변경하였습니다.
- 인증 체크 부분에서 `ResponseEntity.status().body()` 방식 제거
- `CustomException(GlobalErrorCode.UNAUTHORIZED)`를 던지도록 리팩토링
- 글로벌 예외 핸들러를 통해 일관된 에러 응답 형식 유지=
=> refactor: 컨트롤러의 인증 체크 방식을 ResponseEntity → CustomException 로 변경

src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/client/FakeFeedbackCreationClient.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/client/FeedbackCreationClient.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/client/HttpFeedbackCreationClient.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/dto/request/AiFeedbackCreationRequestDto.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/dto/response/AiFeedbackApiResponseDto.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/dto/response/AiFeedbackResponseDto.java
AI 피드백 요청/응답 DTO를 `AiFeedbackCreationRequestDto`, `AiFeedbackApiResponseDto`, `AiFeedbackResponseDto`로 명확하게 구분하고 명명 정비했습니다.
- `FeedbackCreationRequestDto` → `AiFeedbackCreationRequestDto`로 이름 변경
- 응답용 DTO `AiFeedbackApiResponseDto`, `AiFeedbackResponseDto` 분리 및 도입
- 관련 interface (`FeedbackCreationClient`) 및 구현체 수정
=> feat: 피드백 요청/응답 DTO 이름 변경 및 관련 의존성 정리

src/main/java/ktb/leafresh/backend/domain/feedback/application/assembler/FeedbackDtoAssembler.java, src/main/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackCommandService.java
AI 피드백 요청/응답 DTO를 `AiFeedbackCreationRequestDto`, `AiFeedbackApiResponseDto`, `AiFeedbackResponseDto`로 명확하게 구분하고 명명 정비했습니다.
- `FeedbackCreationRequestDto` → `AiFeedbackCreationRequestDto`로 이름 변경
- 응답용 DTO `AiFeedbackApiResponseDto`, `AiFeedbackResponseDto` 분리 및 도입
- 관련 interface (`FeedbackCreationClient`) 및 구현체 수정
=> refactor: client 내부 요청 DTO 및 응답 DTO 변경에 따른 의존성 수정

src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandler.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/FakeChatbotSseStreamHandler.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/HttpChatbotSseStreamHandler.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationSseService.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationSseController.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/util/sse/SseStreamExecutor.java
AI 챗봇 추천 응답을 SSE(Server-Sent Events)로 전달하는 구조를 도입하였습니다.  
FE → BE → AI → BE → FE 흐름에서 AI 응답을 포맷 그대로 프론트에 전달하도록 구현하였습니다.
- `ChatbotRecommendationSseController.java`: `/base-info`, `/free-text` SSE 엔드포인트 추가 (GET)
- `ChatbotRecommendationSseService.java`: AI SSE 응답을 받아 SseEmitter로 프론트에 전달
- `ChatbotSseStreamHandler.java`: SSE 핸들러 인터페이스 정의 (전략 패턴 적용)
- `HttpChatbotSseStreamHandler.java`: 실제 AI 서버와 WebClient 통해 통신하는 구현체
- `FakeChatbotSseStreamHandler.java`: 로컬 개발용 가짜 이벤트 핸들러 (Profile: local)
- `SseStreamExecutor.java`: SSE 비동기 실행 유틸리티 (위치 변경 및 재정비)
- `SecurityConfig.java`: `/api/chatbot/recommendation/**` 경로 인증 제외 처리
=> feat: 챗봇 추천 SSE 응답 중계 구조 도입

src/main/java/ktb/leafresh/backend/domain/store/order/domain/entity/ProductPurchase.java, src/main/java/ktb/leafresh/backend/domain/store/product/domain/entity/Product.java
- products 테이블에 description 필드 추가 및 엔티티 반영
- product_purchases 테이블에 purchased_at 필드 추가
- purchase_price → price, purchase_quantity → quantity로 컬럼명 변경
- product_purchases 테이블에서 BaseEntity 상속 제거
- created_at, updated_at, deleted_at 컬럼 및 관련 인덱스 제거
- 관련 엔티티 필드 및 애노테이션 정리
=> refactor: products 및 product_purchases 테이블 필드 및 인덱스 정비

src/main/java/ktb/leafresh/backend/domain/store/product/domain/entity/enums/ProductStatus.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/ProductRepository.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/controller/ProductAdminController.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/request/ProductCreateRequestDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/response/ProductCreateResponseDto.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
운영자가 일반 상품을 생성할 수 있는 API를 구현하였습니다.  
DTO, Repository, Service, Controller 계층을 포함하며, 상품 상태 관련 코드도 정리하였습니다.
- 일반 상품 생성용 DTO (`ProductCreateRequestDto`) 생성
- 일반 상품 저장을 위한 JPA Repository 추가
- 운영자용 일반 상품 생성 API (`POST /api/admin/products`) 구현
- 상품 상태 코드(Enum 등) 정리 및 리팩토링
=> feat: 운영자용 일반 상품 생성 API 구현

src/main/java/ktb/leafresh/backend/domain/store/product/application/event/ProductUpdatedEvent.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/listener/ProductEventListener.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/ProductUpdateService.java
일반 상품 수정 기능을 구현하고, 생성/수정 이벤트 기반 리스너를 추가하여 후속 처리를 비동기 방식으로 분리하였습니다.
- 일반 상품 수정 로직 구현
- `ProductUpdateRequestDto` 기반 수정 서비스 추가
- 상품 수정 시 발생하는 도메인 이벤트 정의
- `ProductUpdatedEvent` 추가
- 생성/수정 이벤트 처리용 리스너(`ProductEventListener`) 추가
- 상품 정보 변경 후 필요한 후속 작업 트리거 가능하도록 설계
=> feat: 일반 상품 수정 로직 및 이벤트 리스너 추가

src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/domain/entity/TimedealPolicy.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/TimedealPolicyRepository.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/TimedealProductQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/TimedealProductQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/controller/TimedealAdminController.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/request/TimedealCreateRequestDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/response/TimedealCreateResponseDto.java, src/main/java/ktb/leafresh/backend/global/exception/TimedealErrorCode.java
타임딜 상품 등록을 위한 정책 정보를 생성할 수 있도록 도메인, 서비스, API를 구현하였습니다.
- `TimedealPolicy` 엔티티 및 JPA 레포지토리 구현
- `TimedealCreateRequestDto`, `TimedealCreateResponseDto` 생성
- 타임딜 정책 생성 서비스(`TimedealCreateService`) 구현
- 운영자 컨트롤러(`TimedealAdminController`)에 생성 API 추가
- 관련 에러 코드(`TimedealErrorCode`) 정의
=> feat: 운영자용 타임딜 정책 생성 기능 구현

src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealUpdateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheKeys.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheService.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/TimedealProductSummaryCacheDtoMapper.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/dto/TimedealProductSummaryCacheDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/request/TimedealUpdateRequestDto.java
타임딜 정책 수정 기능을 구현하고, 수정 시 관련 상품 목록 캐시를 갱신할 수 있도록 CacheKey, CacheService, 캐싱 DTO 등을 추가하였습니다.
- 타임딜 정책 수정 요청 DTO 추가 (`TimedealUpdateRequestDto`)
- 타임딜 정책 수정 서비스 로직 추가 (`TimedealUpdateService`)
- 상품 캐시 키 상수 클래스 (`ProductCacheKeys`) 추가
- 상품 캐시 무효화를 위한 캐시 서비스 (`ProductCacheService`) 구현
- 타임딜 생성/수정 시 상품 목록, 요약 캐시 제거
- 타임딜 상품 목록 캐싱용 DTO 및 매핑 로직 추가
- `TimedealProductSummaryCacheDto`
- `TimedealProductSummaryCacheDtoMapper`
=> feat: 타임딜 정책 수정 기능 및 상품 캐시 갱신 로직 추가

src/main/java/ktb/leafresh/backend/domain/store/product/application/service/ProductCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/ProductSearchReadService.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductSummaryCacheDtoMapper.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/dto/ProductSummaryCacheDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/ProductSearchQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/controller/ProductController.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/response/ProductListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/response/ProductSummaryResponseDto.java
일반 상품 목록을 조회하는 API를 구현하고, 목록 데이터의 성능 최적화를 위한 캐싱 로직과 DTO/매퍼를 도입하였습니다.  
검색 키워드 기반 조회도 지원합니다.
- 일반 상품 목록 조회용 DTO 추가
- `ProductSummaryResponseDto`, `ProductListResponseDto`
- 일반 상품 목록 캐싱용 DTO 및 매퍼 클래스 추가
- `ProductSummaryCacheDto`, `ProductSummaryCacheDtoMapper`
- 상품 생성 시 목록 캐시에 저장되는 로직 적용
- 일반 상품 검색을 포함한 목록 조회 서비스 및 API 추가
- QueryDSL 기반 Repository, QueryService, ReadService 구현
- Controller API 추가
=> feat: 일반 상품 목록 조회 및 캐싱 기능 구현

src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductPurchaseReadService.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/repository/ProductPurchaseQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/controller/ProductPurchaseController.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/dto/response/ProductPurchaseListResponseDto.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/dto/response/ProductPurchaseSummaryResponseDto.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/repository/ProductSearchQueryRepositoryImpl.java
회원의 상품 구매 이력을 조회하는 API를 구현하였습니다.  
응답 데이터 구성을 위한 DTO 정의부터 레포지토리, 서비스, 컨트롤러까지 전반적인 기능이 포함되어 있습니다.
- 상품 구매 내역 조회 응답 DTO 추가
- `ProductPurchaseSummaryResponseDto`, `ProductPurchaseListResponseDto`
- 구매 내역 조회용 QueryRepository 및 구현체 추가
- 구매 내역 조회 서비스 로직 추가
- `ProductPurchaseQueryService`, `ProductPurchaseReadService` 등
- 구매 내역 조회 API 구현
- `GET /api/mypage/purchases` 또는 해당 컨트롤러 내 목록 조회 엔드포인트 추가
=> feat: 상품 구매 내역 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/member/application/service/MemberUpdateService.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/controller/MemberController.java, src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/MemberUpdateResponseDto.java
회원 정보 수정 API 응답을 기존의 204 No Content에서 200 OK + 수정된 nickname/imageUrl을 포함하는 형태로 변경했습니다.
- MemberUpdateResponseDto 생성 및 빌더 패턴 적용
- MemberUpdateService가 MemberUpdateResponseDto를 반환하도록 변경 (SRP 원칙 반영)
- MemberController에서 상태 코드 200과 응답 본문 포함되도록 수정
=> refactor: 회원 정보 수정 API 응답 204 → 200 OK 및 수정 결과 포함 형태로 변경

src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheKeys.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheService.java, src/main/java/ktb/leafresh/backend/global/initializer/ProductStockCacheInitializer.java, src/main/java/ktb/leafresh/backend/global/initializer/TimedealStockCacheInitializer.java
상품 주문 처리의 성능 향상을 위해 상품 재고 정보를 Redis에 캐싱하는 로직을 구현했습니다.
- `ProductCacheKeys`, `ProductCacheService` 구현
- `ProductStockCacheInitializer` 작성
- `TimedealStockCacheInitializer` 포함
=> feat: 상품 재고 Redis 캐싱 로직 추가

src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/publisher/FakePurchaseMessagePublisher.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/publisher/GcpPurchaseMessagePublisher.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/publisher/PurchaseMessagePublisher.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/subscriber/PurchaseDlqMessageSubscriber.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/subscriber/PurchaseMessageSubscriber.java, src/main/java/ktb/leafresh/backend/global/config/PubSubPublisherConfig.java
상품 주문 요청을 비동기 처리하기 위해 GCP Pub/Sub 기반 publisher 및 subscriber 구조를 도입했습니다. 이를 통해 주문 처리 로직을 메시지 기반으로 분리하고, 확장성과 장애 대응력을 강화했습니다.
- `PurchaseMessagePublisher` 인터페이스 정의 및 구현체(GCP/Fake) 추가
- `PurchaseMessageSubscriber` 클래스 작성하여 메시지 수신 후 주문 처리 연동
- 메시지 처리 상태 및 재시도 로직을 위한 로그 추가
- 기본 Pub/Sub 설정 및 메시지 수신/처리 구조 정립
=> feat: 상품 주문 메시지 Pub/Sub publisher 및 subscriber 구현

src/main/java/ktb/leafresh/backend/domain/store/order/domain/entity/PurchaseIdempotencyKey.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/repository/PurchaseIdempotencyKeyRepository.java
중복된 주문 요청을 방지하기 위해 Idempotency Key 기반의 중복 처리 방지 로직을 도입했습니다. 클라이언트에서 발급한 키를 기준으로 서버에서 선행 요청 여부를 판별할 수 있습니다.
- `PurchaseIdempotencyKey` 엔티티 생성 및 관련 필드 정의
- `PurchaseIdempotencyKeyRepository` 구현
- memberId + idempotencyKey 기준으로 유니크 제약 조건 부여
- 주문 생성 시 이 키를 사용한 중복 요청 차단 로직과 연동
=> feat: 주문 중복 방지를 위한 Idempotency Key 처리 추가

src/main/java/ktb/leafresh/backend/domain/member/domain/entity/Member.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/dto/PurchaseCommand.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductPurchaseProcessingService.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/repository/ProductPurchaseRepository.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/repository/PurchaseProcessingLogRepository.java, src/main/java/ktb/leafresh/backend/global/util/redis/RedisLuaService.java
메시지 큐에서 주문 메시지를 수신한 후, 상품 재고를 차감하고 주문을 처리하는 로직을 구현했습니다.
- `ProductPurchaseProcessingService` 작성
- `ProductPurchaseRepository`를 통한 DB 저장 처리
- `PurchaseCommand`: 메시지 전달용 VO
- `PurchaseProcessingLogRepository`: 처리 로그 저장용 Repository
- `RedisLuaService`: Lua 스크립트를 이용한 원자적 재고 차감 유틸 추가
=> feat: 주문 메시지 소비 후 주문 처리 및 재고 차감 로직 구현

src/main/java/ktb/leafresh/backend/domain/store/order/presentation/controller/ProductOrderController.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/dto/request/ProductOrderCreateRequestDto.java
상품 주문 요청을 처리하는 API 엔드포인트와 DTO, 서비스 진입단을 구현했습니다.
- `ProductOrderController` 생성
- `ProductOrderCreateRequestDto` 작성
=> feat: 일반 상품 주문 생성 API 엔드포인트 구현

src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductPurchaseProcessingService.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/publisher/GcpPurchaseMessagePublisher.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/controller/ProductOrderController.java, src/main/java/ktb/leafresh/backend/global/exception/ProductErrorCode.java, src/main/java/ktb/leafresh/backend/global/exception/PurchaseErrorCode.java
- 멱등키 관련 헤더명을 X-Idempotency-Key → Idempotency-Key로 변경
- 에러 코드 하드코딩을 상수로 추출하여 관리 방식 개선
- 요청 헤더명 변경
- 에러 처리 로직에서 문자열 하드코딩 제거 → ErrorCode 등 상수로 치환
- 코드 일관성 및 유지보수성을 위한 리팩토링 수행
=> refactor: Idempotency-Key 헤더명 및 에러 코드 하드코딩 상수화 리팩토링

src/main/java/ktb/leafresh/backend/domain/store/order/application/dto/PurchaseCommand.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductPurchaseProcessingService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/PurchaseProcessor.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/TimedealOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/model/PurchaseProcessContext.java, src/main/java/ktb/leafresh/backend/domain/store/order/presentation/controller/ProductOrderController.java, src/main/java/ktb/leafresh/backend/domain/store/product/domain/entity/Product.java
타임딜 상품 주문 기능을 일반 상품 주문과 동일한 구조로 구현하였으며, 메시지 발행 및 처리 과정에서도 일관된 방식으로 개선하였습니다.
- `/api/orders/timedeals/{timedealId}` URI 기반 주문 API 엔드포인트 추가
- `TimedealOrderCreateService` 생성 및 타임딜 재고 선점 처리 구현
- 타임딜 정책 유효성(시간, 존재 여부) 검증 로직 추가
- `PurchaseCommand`에 `timedealPolicyId` 필드 추가 및 MQ 메시지 구조 통일
- `ProductPurchaseProcessingService`에서 `timedealPolicyId` 기반 분기 처리
- `PurchaseProcessContext` record 도입으로 프로세스 전달 구조 개선
- `Product` 도메인에 현재 시점 기준 유효한 타임딜 정책 조회 메서드(`getPurchasableTimedealPolicy`) 추가
- 일반 상품 주문 시에도 `timedealPolicyId = null` 명시적으로 전달
- 모든 변경 사항은 기존 일반 주문 구조와 동일한 형태로 구성되어 유지보수 일관성을 고려했습니다.
=> feat: 타임딜 상품 주문 생성 API 구현

build.gradle, src/main/java/ktb/leafresh/backend/BackendApplication.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/cache/VerificationCacheKeys.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/cache/VerificationStatCacheService.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/scheduler/VerificationStatSyncScheduler.java, src/main/java/ktb/leafresh/backend/global/config/ShedLockConfig.java, src/main/java/ktb/leafresh/backend/global/util/redis/VerificationStatRedisLuaService.java
인증글의 좋아요/댓글/뷰 수를 Redis에 임시로 캐싱하고, 일정 주기로 DB에 동기화하는 구조를 구현하였습니다. 중복 스케줄 실행 방지를 위해 ShedLock을 도입하고 Redis 기반 락 설정을 추가했습니다.
- `ShedLock` 의존성 추가 및 `RedisLockProvider` 설정 (`ShedLockConfig`)
- 인증 통계 캐싱 키 유틸 클래스 (`VerificationCacheKeys`)
- 좋아요 및 댓글 수 증감용 Redis Hash 캐싱 로직 (`VerificationStatCacheService`)
- Lua 스크립트를 활용한 뷰 수 증가 및 TTL 설정 처리 (`VerificationStatRedisLuaService`)
- ShedLock을 이용한 통계 DB 동기화 스케줄러 구현 (`VerificationStatSyncScheduler`)
- `@EnableSchedulerLock` 및 관련 어노테이션 추가 (`BackendApplication`)
=> feat: 인증 통계 Redis 캐싱 및 ShedLock 기반 동기화 기능 구현

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeVerificationReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeVerificationReadController.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeVerificationDetailResponseDto.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/LikeRepository.java, src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java, src/main/java/ktb/leafresh/backend/global/exception/VerificationErrorCode.java
단체 챌린지 인증글의 상세 정보를 반환하는 API를 구현하였습니다. 응답에는 작성자 정보, 인증 이미지 및 내용, 통계 정보(조회수/댓글수/좋아요 수), 좋아요 여부 등을 포함합니다.
- `GroupChallengeVerificationDetailResponseDto`: 상세 응답 DTO 생성
- `GroupChallengeVerificationQueryRepository`: 인증글 단건 조회 메서드 추가
- `GroupChallengeVerificationReadService`: Redis 캐싱된 통계 + 좋아요 여부 병합 처리
- `GroupChallengeVerificationReadController`: `/verifications/{verificationId}` GET API 추가
- `SecurityConfig`: API 경로에 인증 설정 반영
- `VerificationErrorCode`: 인증글 미존재 및 쿼리 실패 예외 추가
=> feat: 단체 챌린지 인증글 상세 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentCreateService.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupVerificationCommentManageController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/GroupVerificationCommentCreateRequestDto.java, src/main/java/ktb/leafresh/backend/global/exception/VerificationErrorCode.java
단체 챌린지 인증글에 대댓글을 작성할 수 있는 기능을 구현하였습니다. 사용자 인증을 기반으로, 특정 댓글에 대한 자식 댓글(대댓글)을 작성할 수 있습니다.
- `/api/challenges/group/{challengeId}/verifications/{verificationId}/comments/{commentId}/replies` POST API 추가
- 대댓글 생성 비즈니스 로직 및 Service, Controller 구현
- 부모 댓글 존재 여부 및 삭제 여부 검증 로직 추가
- 삭제된 부모 댓글에 대댓글 작성 시 에러 반환 (에러 코드 추가)
- `@NotBlank` 메시지 문구 수정
=> feat: 단체 챌린지 인증글 대댓글 생성 API 구현

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationLikeService.java, src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/Like.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/LikeRepository.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupVerificationLikeController.java
단체 챌린지 인증글에 대해 좋아요를 누를 수 있는 기능을 구현했습니다.  
소프트 삭제된 좋아요 복구, Redis 통계 동기화까지 포함하여 실제 서비스 흐름에 맞게 구현되었습니다.
- Like 엔티티에 유니크 제약 조건 및 soft delete 복구 메서드 추가
- 인증글 ID별 좋아요 수 조회, 특정 멤버의 좋아요 조회 등을 위한 쿼리 메서드 추가
- 인증글 좋아요 서비스 로직 구현
- 이미 좋아요한 경우 true 반환
- soft delete된 좋아요는 복구 처리
- Redis에 좋아요 수 증가 처리 포함
- 인증글 좋아요 API 컨트롤러 구현
- `POST /api/challenges/group/{challengeId}/verifications/{verificationId}/likes`
- 응답: `{ isLiked: true }`
- 중복 좋아요 방지를 위해 memberId + verificationId에 유니크 제약 설정
- 복구 시에는 `restoreLike()` 호출 후 Redis에 좋아요 수 반영
=> feat: 단체 챌린지 인증글 좋아요 API 구현

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentDeleteService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/CommentRepository.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupVerificationCommentManageController.java
단체 챌린지 인증글에 달린 댓글의 삭제 및 조회 기능을 구현하였습니다.  
댓글의 소프트 삭제 처리와 Redis 내 댓글 수 캐싱 반영까지 포함됩니다.
- `CommentRepository`
- 댓글 수 집계를 위한 `verificationId` 그룹별 카운트 쿼리 추가
- 대댓글 계층 조회 및 작성자 정보 fetch를 위한 JPQL 추가
- `GroupVerificationCommentDeleteService`
- 댓글 작성자 본인 여부 확인
- 이미 삭제된 댓글 여부 확인
- soft delete 수행 및 Redis 댓글 수 감소 반영
- `GroupVerificationCommentQueryService`
- 인증글 ID 기반 전체 댓글 조회 및 작성자 정보 포함 fetch
- 계층 구조(`CommentHierarchyBuilder`)로 변환 후 응답
- `GroupVerificationCommentManageController`
- 댓글 삭제 API 연결
- 댓글 목록 조회 API(`GET /api/challenges/group/{challengeId}/verifications/{verificationId}/comments`) 구현
=> feat: 댓글 삭제 및 조회 API 구현

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationSubmitService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationSubmitService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadService.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/GroupChallengeVerificationRepository.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/repository/PersonalChallengeVerificationRepository.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/VerificationCountController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/response/VerificationCountResponseDto.java, src/main/java/ktb/leafresh/backend/global/exception/VerificationErrorCode.java, src/main/java/ktb/leafresh/backend/global/initializer/VerificationCountInitializer.java
- 누적 사용자 인증 수 조회 성능을 개선하기 위해 Redis 캐싱을 도입했습니다.
- DB 조회 → Redis 초기화 → 인증 발생 시 증가 처리 흐름을 구성했습니다.
- `VerificationCountQueryService`: 전체 인증 수를 DB에서 조회하도록 구현 (group + personal 합산)
- `VerificationCountInitializer`: 서버 시작 시 DB에서 조회한 전체 인증 수를 Redis에 캐싱
- `VerificationCountReadService`: Redis에서 인증 수 조회 (조회용 서비스)
- `VerificationCountController`: 인증 수 조회 API에서 `VerificationCountReadService`를 사용하도록 수정
- `GroupChallengeVerificationSubmitService`, `PersonalChallengeVerificationSubmitService`:
- 인증 제출 성공 시 Redis에서 인증 수 `INCR` 처리
- Redis 업데이트 실패 시에도 서비스 로직은 영향 없이 진행되도록 예외 캐치 처리
- `VerificationErrorCode`: `VERIFICATION_COUNT_QUERY_FAILED` 추가
- `GroupChallengeVerificationRepository`, `PersonalChallengeVerificationRepository`: `countAll()` 쿼리 추가
=> feat: 누적 인증 수 Redis 캐싱 및 초기화/증가 처리 로직 구현

src/main/java/ktb/leafresh/backend/domain/auth/application/service/oauth/OAuthLoginService.java, src/main/java/ktb/leafresh/backend/global/exception/GlobalErrorCode.java
소셜 로그인 요청 시 전달되는 origin 값이 허용된 도메인인지 검증하여 악의적인 요청을 차단하고, 유효하지 않은 origin에 대해 별도의 에러 코드를 반환하도록 처리했습니다.
- `OAuthLoginService#getRedirectUrl()` 내부에 origin 화이트리스트 검증 로직 추가
- 허용된 도메인 목록: `local.dev-leafresh.app`, `dev-leafresh.app`, `leafresh.app`
- `GlobalErrorCode.INVALID_ORIGIN` 에러 코드 정의 (400 Bad Request)
- origin 누락 시 fallback 도메인(`https://leafresh.app`) 적용 로직 유지
- 허용된 origin → 정상 `redirectUrl` 응답
- 허용되지 않은 origin → 400 응답 + `"허용되지 않은 origin입니다."` 메시지 확인
- 도메인 리스트는 추후 `application.yml` 기반 관리로 리팩토링 가능
=> feat: 소셜 로그인 origin 화이트리스트 검증 및 에러 코드 추가

src/main/java/ktb/leafresh/backend/global/security/AuthCookieProvider.java
- `AuthCookieProvider`에 `@Value("${cookie.domain}")` 추가
- `createCookie`, `clearCookie` 메서드에 `.domain(domain)` 설정
- `application-docker-local.yml` 및 `.env.docker-local`의 `cookie.domain` 반영
- SameSite=None 환경에서 cross-origin 쿠키가 정상적으로 브라우저에 저장되지 않는 문제 해결
- 로그인 이후 쿠키가 클라이언트에 정상 전달되지 않아 401 Unauthorized가 발생하던 이슈 해결
- OAuth 로그인 후 브라우저 네트워크 탭에서 `Set-Cookie` 헤더 내 `Domain=.dev-leafresh.app` 확인
- Postman 쿠키 요청 시 200 응답 정상 확인
=> feat: 쿠키에 domain 설정 추가 (.dev-leafresh.app)

src/main/java/ktb/leafresh/backend/global/config/RedisBloomConfig.java, src/main/resources/application-docker-local.yml, src/main/resources/application-local.yml
- RedisBloomConfig에 하드코딩된 "localhost:6379"를 제거하고, @Value 주입 방식으로 수정
- application-local.yml, application-docker-local.yml에 redis.bloom.host 및 redis.bloom.port 프로퍼티 추가
- 로컬/도커 환경에 따라 RedisBloom 접근 주소를 `.env`를 통해 쉽게 설정 가능하도록 개선
- 운영 환경에서는 RedisBloom이 Docker 컨테이너 내부에서 동작하고 있기 때문에, 내부 IP 연결이 필요함
- 기존에는 localhost로 고정되어 있어 GCE 환경에서 연결 오류 발생
- 이를 `.yml` 외부 설정으로 분리하여, 환경마다 커스텀 가능하게 구성함
- 로컬 환경(local profile)에서 RedisBloom 정상 연결 확인 (`localhost:6379`)
- 향후 서버 배포 시 application-docker-local.yml 기반으로 내부 IP 대응 가능
=> feat: RedisBloomConfig에 외부 설정 주입 적용 및 환경별 호스트 구성

src/main/java/ktb/leafresh/backend/domain/member/presentation/dto/response/MemberInfoResponseDto.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/MemberInfoQueryServiceTest.java
회원 정보 조회 API(`/api/members`) 응답에 이메일(email) 필드를 포함시켰습니다.
- `MemberInfoResponseDto`에 `email` 필드 추가
- `MemberInfoResponseDto.of()`에서 `member.getEmail()` 매핑
- 단위 테스트(`MemberInfoQueryServiceTest`)에서 `email` 검증 항목 추가
=> feat: 회원 정보 조회 응답에 이메일 필드 추가

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCategoryService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeSummaryResponseDto.java
- 단체 챌린지 목록 응답 DTO (`GroupChallengeSummaryResponseDto`)에 `category`, `description` 필드 추가
- category: 챌린지에 연결된 GroupChallengeCategory의 name
- description: 챌린지 상세 설명
- 기존 GroupChallengeCategory 목록에서 `ALL` 카테고리를 수동 삽입하던 로직 제거
- DB `sequence_number` 기준으로 정렬되도록 보장
- 챌린지 목록 카드에서 카테고리와 설명을 프론트엔드 UI에 바로 바인딩할 수 있도록 하기 위함
=> feat: 단체 챌린지 목록에 category 및 description 필드 추가

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationSseService.java
- ChatbotRecommendationSseService 클래스에서 aiServerBaseUrl 필드가 생성자 주입으로만 선언되어 있어 Spring config로부터 값이 주입되지 않음
- 이로 인해 SSE 요청 시 AI 서버로 전달되는 URI가 null로 시작되어 400 또는 401 에러 발생
- aiServerBaseUrl에 @Value("${ai-server.base-url}") 어노테이션을 추가하여 application.yml에서 설정한 값이 주입되도록 수정
=> Fix: Chatbot SSE API AI 서버 baseUrl 주입 오류 해결

src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealProductReadService.java
타임딜 목록 조회 시 ONGOING 상태의 타임딜이 누락되는 문제를 해결하기 위해
ZSet 범위 조회 기준을 보완하고, 상태값을 동적으로 판단하는 로직을 추가했습니다.
- Redis ZSet 조회 시 now → twoHoursBeforeNow 기준으로 확장하여 시작된 타임딜 포함
- Redis 캐시된 TimedealProductSummaryDto의 startTime/endTime을 기반으로
현재 시각 기준 상태를 ONGOING/UPCOMING으로 동적 재계산
- 기존 캐시 TTL 구조 유지
- DB 상 startTime이 현재 시각과 정확히 같은 타임딜이 정상적으로 목록에 포함됨
- 상태값도 정확히 ONGOING으로 표시되는 것 확인
- 타임딜 노출 시간 임계점(시작 시각 = 현재 시각)에서 목록 누락되는 현상
=> fix: 타임딜 목록 조회에서 ZSet 범위 확장 및 상태값 실시간 계산 추가

src/main/resources/application.yml
- `application.yml`에 `spring.jackson.time-zone: Asia/Seoul` 설정 추가
- Jackson 직렬화 시 응답 시간 기준을 UTC → KST로 통일
- 서버/JVM 시간대를 KST로 변경함에 따라 JSON 응답에도 KST 기준 반영 필요
- 기존에는 응답에 포함된 `LocalDateTime`이 UTC 기준으로 직렬화되어 9시간 오차 발생
- 클라이언트 화면에서 타임딜 시작/종료 시간이 실제 한국 시간대로 표시됨
- 시간 기준 오해로 인한 사용자 혼란 제거
=> chore: Jackson 직렬화 시간대를 Asia/Seoul(KST)로 설정

src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandlerImpl.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationSseService.java
- SseEmitter 생성 시 `.onCompletion`, `.onTimeout`, `.onError` 핸들러 추가
- SSE 응답 전송 중 `Broken pipe` 등의 예외 발생 시 `completeWithError()` 호출하도록 처리
- WebClient `subscribe()` 구독 흐름에서 `onNext`, `onError`, `onComplete` 분기 로직 명확화
- 클라이언트(프론트)가 SSE 연결을 끊었을 경우 발생하는 `IOException`, `AsyncRequestNotUsableException` 대응
- 백엔드에서 해당 예외가 발생해도 서버 오류로 확산되지 않도록 방지
- 안정적인 챗봇 SSE 스트리밍을 위한 흐름 보완
=> fix: 챗봇 SSE 연결 종료 시 예외 처리 로직 추가

src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandlerImpl.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/HttpChatbotSseStreamHandler.java
기존 SSE 핸들러가 profile에 따라 두 개로 분리되어 있던 구조를 단일화했습니다.
- ChatbotSseStreamHandlerImpl 클래스에 SSE 중계 로직 통합
- event/data 구조를 그대로 유지하여 프론트엔드에서 SSE 수신 가능
- 불필요한 문자열 조립 방식 제거 및 WebClient 요청 정리
- 기존 HttpChatbotSseStreamHandler 완전 제거
=> refactor: 챗봇 SSE 핸들러 단일 구현체로 통합 및 기존 Http 핸들러 제거

src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/service/GroupChallengeVerificationHistoryCalculator.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeParticipationRecordQueryRepositoryImpl.java
- `/api/members/challenges/group/participations/count` 에서 not_started 조건을 '참여했으나 인증 이력이 없는 경우'로 수정
- `/participations/{challengeId}/verifications`의 remaining 값을 (endDate - 오늘 + 1)로 계산하며, 음수 방지를 위해 Math.max(0, ...) 적용
- 챌린지 시작일이 지난 후에도 인증을 하지 않은 사용자가 not_started로 분류되지 않는 문제 해결
- 인증 마감일이 지났음에도 remaining이 음수로 표기되던 문제 해결
- 참여 상태 카운트 API
- 챌린지 인증 내역 조회 API
=> fix: 참여한 단체 챌린지 not_started 조건 및 remaining 계산 방식 수정

src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationSseController.java
- SSE 응답이 nginx 프록시를 거칠 때 실시간 스트리밍이 유지되도록 하기 위해,
`ChatbotRecommendationSseController`에 `Cache-Control: no-cache` 및 `X-Accel-Buffering: no` 헤더를 명시적으로 추가했습니다.
- HTTP 응답 헤더 설정은 `HttpServletResponse` 객체를 통해 처리했습니다.
- nginx에서 기본적으로 response buffering이 활성화되어 있어, SSE의 실시간 스트리밍이 차단될 수 있음
- `X-Accel-Buffering: no` 설정을 통해 nginx의 버퍼링을 비활성화
- `Cache-Control: no-cache`는 브라우저 캐싱 방지 및 실시간 수신 유지를 위해 필요
- 적용 대상 URI: `/api/chatbot/recommendation/base-info`, `/free-text`
=> fix: SseEmitter 응답 시 Cache-Control 및 X-Accel-Buffering 헤더 설정

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeParticipationReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepository.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepositoryImpl.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeParticipationSummaryDto.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationSseController.java
- 프론트 요청에 따라 참여한 단체 챌린지 목록 응답에서 `createdAt` 필드를 제거했습니다.
- 인증 이력(`achievementRecords`)을 챌린지별로 그룹핑하여 응답에 포함할 수 있도록 새로운 쿼리 메서드를 추가했습니다.
- `GroupChallengeParticipationSummaryDto`에서 `createdAt`에 `@JsonIgnore` 적용
- 커서 기반 페이지네이션에는 사용되지만 응답에서는 제외
- 인증 이력을 챌린지별로 그룹핑하여 `List<AchievementRecordDto>`로 반환하는 메서드 추가
- `createdAt` 오름차순 정렬 → 가장 오래된 인증이 `day 1`
- 반복 순서를 기반으로 `day` 값 부여
- `GroupChallengeVerificationQueryRepository`에 시그니처 추가
- `GroupChallengeParticipationReadService`에서 인증 이력 매핑 방식 개선
- 환경 분기용 `@Profile(local/docker)` 추가 (부가 작업)
=> feat: 단체 챌린지 인증 이력 조회 메서드 추가 및 createdAt 응답 제거

src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealProductReadServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealUpdateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentUpdateServiceTest.java
- 테스트 중 createdAt, updatedAt 필드가 null이거나 타입 불일치로 인해
atOffset(ZoneOffset.UTC) 호출 시 NullPointerException이 발생하던 문제를 해결
- ReflectionTestUtils.setField(...)를 사용해 LocalDateTime 값을 명시적으로 설정
- Timedeal, Comment 관련 테스트에서 OffsetDateTime → LocalDateTime 변환을 반영
=> test: OffsetDateTime 기반 응답 DTO 테스트 오류 수정

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeParticipationReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/query/GroupChallengeParticipationDto.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeParticipationSummaryDto.java
비즈니스 로직에서는 `LocalDateTime`, 프론트엔드 응답 및 커서 기반 페이지네이션에서는 `OffsetDateTime`을 사용하도록 타입을 분리했습니다.
- `GroupChallengeParticipationDto`의 `createdAt`을 `LocalDateTime`으로 변경
- `GroupChallengeParticipationSummaryDto`의 `createdAt`을 `OffsetDateTime`으로 변경
- `GroupChallengeParticipationReadService`에서 `OffsetDateTime.of(..., ZoneOffset.UTC)` 변환 처리
- 커서 추출 시 `.toLocalDateTime()` 적용하여 CursorPaginationHelper의 시그니처와 타입 일치
- QueryDSL의 constructor projection은 `OffsetDateTime` 매핑 시 런타임 오류 발생 가능성이 있음
- DB의 `TIMESTAMP` 컬럼은 `LocalDateTime`으로 매핑되는 것이 자연스럽고 안정적임
- 응답에는 명시적인 시간대 정보가 포함된 `OffsetDateTime`(UTC) 사용이 적절함
=> refactor: 참여 챌린지 DTO의 createdAt 타입 분리

build.gradle, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealProductReadService.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheService.java, src/main/java/ktb/leafresh/backend/global/config/RedisConfig.java, src/main/resources/application-docker-local.yml, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateServiceTest.java
- 타임딜 목록 조회 시 ZSet/단건 캐시가 모두 비어 있는 경우, DB fallback을 통해 캐시 재구축
- 일반 상품 재고 조회 시 Redisson 분산락 기반의 캐시 등록 로직 추가
- ProductOrderCreateService에 fallback 로직 적용하여 캐시 스탬피드 방지
- 관련 의존성/설정 추가 및 테스트 수정 포함
- `TimedealProductReadService`
- ZSet 캐시 범위 조회 후 단건 캐시 확인
- 단건 캐시 MISS 시 DB에서 조회 후 다시 캐시 등록
- ZSet 자체도 비어있는 경우 → `findUpcomingOrOngoingWithinWeek()` 호출로 완전 복구
- 최종적으로 목록 캐시 저장 및 상태 갱신
- `ProductCacheService`
- `getProductStockWithDistributedLock()` 추가 (Redisson 락 기반 double-check 캐시 등록)
- 일반 상품 재고 캐시 TTL 추가 설정
- `ProductOrderCreateService`
- 상품 주문 시 재고 캐시 미존재 대비 fallback 호출 추가
- 캐시 없는 상태에서의 스탬피드 문제 방지
- `RedisConfig`
- `redissonClient` 등록을 위한 설정 추가 (`redis.redisson.address` 기반)
- `application-local.yml`, `application-docker-local.yml`
- redisson address 환경변수 구조 통일
- 중복된 `redis:` 루트 제거
- 테스트 코드
- …
=> refactor: 타임딜 조회 및 일반 상품 재고 캐싱 개선

src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeVerificationDetailResponseDto.java
인증 상세 조회 API에서 `verifiedAt`이 null일 경우 NPE가 발생하던 문제를 수정했습니다.
- `GroupChallengeVerificationDetailResponseDto.from()` 메서드에서 `verifiedAt`을 null-safe 처리
- 향후 nullable 필드에 대해 방어적 코딩 적용
=> fix: 인증 상세 조회 시 verifiedAt null 처리

src/main/java/ktb/leafresh/backend/domain/member/application/service/LeafPointReadService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/PurchaseProcessor.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadService.java, src/main/java/ktb/leafresh/backend/global/initializer/LeafPointInitializer.java, src/main/java/ktb/leafresh/backend/global/initializer/VerificationCountInitializer.java
- Redis 캐시 스탬피드 방지를 위해 Redisson 기반 분산 락 적용
- 누적 나뭇잎 수, 누적 인증 수 캐시 TTL 24시간으로 설정하여 DB 부하 최소화
- 타임딜 구매 성공 시 단건 캐시 자동 갱신 처리
- `LeafPointReadService` / `VerificationCountReadService`에 Redisson `tryLock` 적용
- 락 획득 실패 시 short sleep 후 재시도 방식으로 fail-safe 처리
- TTL 미설정 상태였던 누적 캐시 데이터에 TTL 24시간 추가 적용
- `PurchaseProcessor` 내 타임딜 구매 성공 후 캐시된 상품 요약 정보 갱신 로직 추가
- 락 키는 `lock:leafresh:totalLeafPoints:sum`, `lock:leafresh:totalVerifications:count` 형식으로 prefix 일관성 유지
- 향후 공통 분산 캐시 fallback 유틸로 리팩토링 고려 가능
=> refactor: 누적 나뭇잎·인증 수 캐시 TTL 적용 및 RedissonLock 기반 fallback 처리

src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/scheduler/VerificationStatSyncScheduler.java, src/main/java/ktb/leafresh/backend/global/config/RedisConfig.java, src/main/java/ktb/leafresh/backend/global/config/RedissonConfig.java, src/main/java/ktb/leafresh/backend/global/lock/annotation/DistributedLock.java, src/main/java/ktb/leafresh/backend/global/lock/aop/AopForTransaction.java, src/main/java/ktb/leafresh/backend/global/lock/aop/DistributedLockAop.java, src/main/java/ktb/leafresh/backend/global/lock/util/CustomSpringELParser.java
VerificationStatSyncScheduler에 Redisson 기반 분산락을 AOP 방식으로 적용하였습니다. 기존의 tryLock → unlock 처리 및 중복 로직을 제거하고, 선언적 분산락 구조로 리팩토링하였습니다.
- `@DistributedLock` 어노테이션 정의 및 AOP 적용
- `AopForTransaction` 클래스 추가 (REQUIRES_NEW 트랜잭션 실행용)
- `CustomSpringELParser` 유틸로 SpEL 기반 키 추출 지원
- `RedissonConfig` 클래스 추가하여 RedissonClient 빈 분리
- VerificationStat 서비스의 직접 락 처리 제거 후 AOP 방식으로 일원화
- 기존 `ShedLock` 적용된 `VerificationStatSyncScheduler`는 유지하면서, 병렬 처리 구간인 `syncStat`에만 분산락 적용하였습니다.
- 분산락 키는 `"lock:{prefix}"` 형태로 설정되어 있음
=> feat: Redisson 분산락 AOP 구현 및 VerificationStat 도메인 적용

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeVerificationReadService.java, src/main/java/ktb/leafresh/backend/domain/member/application/service/LeafPointReadService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/facade/ProductCacheLockFacade.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/order/application/service/TimedealOrderCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/listener/ProductEventListener.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/ProductCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/ProductUpdateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealCreateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealUpdateService.java, src/main/java/ktb/leafresh/backend/domain/store/product/infrastructure/cache/ProductCacheService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadService.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/scheduler/VerificationStatSyncScheduler.java, src/main/java/ktb/leafresh/backend/global/exception/GlobalErrorCode.java, src/main/java/ktb/leafresh/backend/global/initializer/ProductStockCacheInitializer.java, src/main/java/ktb/leafresh/backend/global/initializer/TimedealStockCacheInitializer.java, src/main/java/ktb/leafresh/backend/global/lock/aop/DistributedLockAop.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/LeafPointReadServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/order/application/service/ProductOrderCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/ProductCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/ProductUpdateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealUpdateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadServiceTest.java
- 분산락의 책임을 서비스 레이어에서 제거하고, `ProductCacheLockFacade`로 일원화했습니다.
- 기존 `@DistributedLock`이 서비스 메서드에 직접 걸려 있던 구조를 제거하고, 모든 락 로직을 파사드 내부로 이동시켰습니다.
- 대표적으로 `ProductOrderCreateService`, `TimedealCreateService`, `TimedealUpdateService` 등이 파사드를 사용하도록 변경되었습니다.
- `ProductCacheService` 내부의 `getProductStockWithDistributedLock()` 메서드는 제거하고, 단순 캐싱 메서드로 대체했습니다.
- 관련된 테스트 코드도 모두 `ProductCacheLockFacade` mock을 활용하는 방식으로 수정했습니다.
- 분산락 처리 위치가 명확해지고, SRP 원칙을 준수합니다.
- 락 중복 및 의도치 않은 이중락 방지
- 테스트, 유지보수, 로깅 모두에서 책임 구분이 뚜렷해집니다.
- 주문 생성: `ProductOrderCreateServiceTest`
- 타임딜 생성/수정: `TimedealCreateServiceTest`, `TimedealUpdateServiceTest`
- 기타 캐시 관련 테스트: `ProductCreateServiceTest`, `ProductUpdateServiceTest`
=> refactor: 분산락 책임을 Facade로 일원화

src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/client/HttpAiChallengeValidationClient.java, src/main/java/ktb/leafresh/backend/global/config/WebClientConfig.java, src/main/resources/application.yml
기존 imageAiWebClient는 인증 이미지 검열과 챌린지 생성 검열을 모두 처리하고 있었지만,
챌린지 검열 서버가 별도로 분리됨에 따라 전용 WebClient를 추가했습니다.
- .env.docker-local: `make_challenge_ai_server_base_url` 환경변수 추가
- application.yml: `ai-server.make-challenge-base-url` 항목 추가
- WebClientConfig: `makeChallengeAiWebClient` Bean 등록
- HttpAiChallengeValidationClient: 해당 WebClient로 교체 주입
=> feat: 챌린지 생성 검열용 makeChallengeAiWebClient 분리 및 설정 반영

.gitignore, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/subscriber/PurchaseDlqMessageSubscriber.java, src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/subscriber/PurchaseMessageSubscriber.java, src/main/resources/application-docker-local.yml, src/main/resources/application-docker-prod.yml
- 기존 Pub/Sub 구독 구성을 위한 Subscription ID 하드코딩 제거
- `.env.docker-{env}` 파일에 `gcp_pubsub_subscription_order`, `gcp_pubsub_subscription_order_dlq` 추가
- `application-docker-{env}.yml`에 `gcp.pubsub.subscriptions.order`, `dlq` 설정 추가
- `PurchaseMessageSubscriber`, `PurchaseDlqMessageSubscriber`에 `Environment` 주입 및 설정값 기반 구독 적용
운영/개발 환경에 따라 구독 설정을 분리하여 유연한 배포 및 유지보수 지원
=> refactor: GCP Pub/Sub 구독 설정 환경변수화 및 하드코딩 제거

src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandler.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandlerImpl.java, src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationSseService.java, src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationSseController.java, src/main/resources/application-docker-prod.yml
- 기존 `@Profile("docker-local")`로 dev 환경에서만 사용되던 SSE 기반 챗봇 API를 더 이상 사용하지 않음에 따라 `@Profile("unused")`로 변경
- 빈 등록이 되지 않도록 처리하면서도, 코드 자체는 보존하여 추후 필요 시 재활성화 가능
- 관련 컨트롤러, 서비스, 핸들러 클래스 전체에 일괄 적용
- 향후 SSE 방식 복구 또는 테스트 시 간편하게 다시 사용할 수 있도록 클래스 및 주석 유지
=> chore: SSE 기반 챗봇 추천 기능 @Profile("unused")로 비활성화 처리

build.gradle, src/main/resources/application.yml
- Prometheus를 통한 메트릭 수집을 위해 actuator에 prometheus endpoint 추가
- application.yml:
- `management.endpoints.web.exposure.include`에 prometheus 포함
- `management.endpoint.prometheus.access`를 `unrestricted`로 설정하여 인증 없이 접근 가능
- build.gradle:
- `io.micrometer:micrometer-registry-prometheus` 의존성 추가
- Spring Boot 3.4.5 기준 설정 방식
- `access: public`은 유효하지 않으며, `unrestricted` 사용
=> feat: Prometheus metrics endpoint 활성화 설정 추가

build.gradle, src/main/resources/application-local.yml
- SQL 로그 확인을 위한 p6spy 의존성 추가
- application-local.yml에 p6spy 관련 datasource logging 설정 추가
- GCP Pub/Sub topic 및 subscription 관련 환경 변수 설정 추가
- 개발 시 SQL 로그 추적을 통해 디버깅 용이성 향상
- GCP Pub/Sub 연동에 필요한 토픽/서브스크립션 설정값 분리 관리
- 별도 활성화 profile에 따라 운영 환경에 영향 없음
=> feat: p6spy 및 GCP Pub/Sub 설정 추가

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupChallengeVerificationSubmitController.java, src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/PersonalChallengeVerificationSubmitController.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultQueryServiceTest.java
기존에는 인증 결과를 pollingExecutor를 통해 비동기적으로 대기하는 구조였으나,
단건 조회(getLatestStatus)를 직접 호출하도록 구조를 단순화했습니다.
- `ChallengeVerificationPollingExecutor` 제거
- `waitForResult()` → `getLatestStatus()` 직접 호출로 변경
- 테스트 코드에서 pollingExecutor 관련 mock/stub 제거
- 컨트롤러 로직도 pollingExecutor 기반에서 단건 조회 방식으로 전환
- 인증 결과 응답 시간 단축
- pollingExecutor 제거로 인한 불필요한 complexity 해소
- 테스트 코드 간결화 및 유지 보수성 향상
=> refactor: 챌린지 인증 결과 조회 시 pollingExecutor 제거 및 동기 방식으로 변경

src/main/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackResultQueryService.java, src/main/java/ktb/leafresh/backend/domain/feedback/presentation/controller/FeedbackResultController.java, src/test/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackResultQueryServiceTest.java
기존 피드백 결과 조회는 pollingExecutor를 통해 결과 생성을 기다리는 방식이었으나,  
단건 조회(getFeedbackResult)를 즉시 수행하는 방식으로 단순화하여 응답 속도 및 가독성을 개선했습니다.
- FeedbackPollingExecutor 및 관련 의존성 제거
- waitForFeedback() 제거 및 getFeedbackResult() 메서드로 직접 조회
- 컨트롤러에서 waitForFeedback() → getFeedbackResult() 호출로 변경
- Redis 캐시, DB 단건 조회 기반 로직 유지
- 테스트 코드도 pollingExecutor 관련 mock 제거 및 시나리오 재작성
- 불필요한 polling 제거로 코드 간결화
- 테스트 안정성 및 속도 개선
- 가독성 향상 및 유지보수성 향상
=> refactor: 피드백 결과 조회 시 pollingExecutor 제거 및 단건 조회 방식으로 리팩토링

src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationFeedServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationSubmitServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentDeleteServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentUpdateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationLikeServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountQueryServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadServiceTest.java, src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationResultProcessorTest.java
- 인증 도메인 테스트 코드에 대해 내부 테스트 스타일 통일 작업을 진행했습니다.
- `@Mock`, `@InjectMocks` 기반 테스트 구조 통일
- Fixture 객체의 ID, 시간 등 불필요한 설정 제거
- `assertThat(응답).isEqualTo(하드코딩)` → 객체 기반 검증 방식으로 수정
- 에러 메시지 비교 시 `ErrorCode.getMessage()` 기반 검증 방식 도입
- 시간 비교 시 `LocalDateTime.now()` → 고정값으로 대체
=> refactor: 인증 도메인 테스트 코드 스타일 통일

src/test/java/ktb/leafresh/backend/domain/challenge/personal/application/factory/PersonalChallengeExampleImageAssemblerTest.java, src/test/java/ktb/leafresh/backend/domain/challenge/personal/application/factory/PersonalChallengeFactoryTest.java, src/test/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeCreateServiceTest.java, src/test/java/ktb/leafresh/backend/domain/challenge/personal/application/service/PersonalChallengeReadServiceTest.java, src/test/java/ktb/leafresh/backend/support/fixture/PersonalChallengeExampleImageFixture.java
- 테스트용 Fixture 클래스 구현
- PersonalChallengeReadService 등 단위 테스트 작성
- 챌린지 목록 조회 (정상/예외)
- 챌린지 상세 조회 (로그인/비로그인/예외)
- 챌린지 규칙 조회 및 인증 이력 조회 (정상/예외)
- 시간 비교는 LocalDateTime 고정값 사용하여 테스트 안정성 확보
=> test: 개인 챌린지 도메인 픽스처 및 테스트 코드 추가

src/main/java/ktb/leafresh/backend/domain/store/order/infrastructure/subscriber/PurchaseMessageSubscriber.java
- `PurchaseMessageSubscriber`에서 `googclient_deliveryattempt` 값이 5 이상인 경우, `consumer.nack()`을 호출하여 DLQ로 이동시키던 기존 로직을 제거하고, `consumer.ack()`으로 처리되도록 수정
- DLQ 대상 메시지 처리에서 무한 재시도 방지 및 안정적인 로그 적재를 위해 반드시 ack 처리
- 관련 로그 상세화: DLQ 대상 여부와 메시지 ID 출력
- Pub/Sub 메시지를 5회 이상 재전송해도 처리되지 않으면 DLQ로 이동해야 하지만, `consumer.nack()` 호출 시 GCP Pub/Sub가 메시지를 계속 재전송하여 무한 루프 발생
- DLQ 설정이 되어 있어도 `nack()`만 호출하면 Pub/Sub는 메시지를 ack 되지 않은 상태로 인식하여 재전송을 반복함
- DLQ 대상 메시지는 조건 확인 후 `consumer.ack()`을 호출하여 정상적으로 DLQ로 이동하도록 처리
- DLQ 대상 여부 확인 로직은 그대로 유지하되, 실제 메시지 응답은 ack 처리
=> fix: 구매 메시지 처리 시 DLQ 대상 메시지 ack 누락으로 인한 무한 재시도 현상 해결

src/main/java/ktb/leafresh/backend/domain/member/application/service/RewardGrantService.java, src/main/java/ktb/leafresh/backend/domain/member/domain/entity/Member.java, src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/TreeLevelRepository.java, src/test/java/ktb/leafresh/backend/domain/member/application/service/RewardGrantServiceTest.java
- 나뭇잎 누적 포인트(totalLeafPoints)가 TreeLevel 조건을 넘었음에도 프로필 카드에서 레벨이 반영되지 않는 문제를 해결하기 위함입니다.
- `RewardGrantService`에 `TreeLevelRepository` 주입 및 레벨 업데이트 로직 추가
- 포인트 지급 시 현재 보유 포인트에 맞는 TreeLevel을 조회하고, 기존 레벨과 다르면 자동으로 갱신
- 로그로 레벨 변경 내역 확인 가능
- `Member` 엔티티에 `updateTreeLevel(TreeLevel)` 메서드 추가
- `TreeLevelRepository`에 포인트 기준으로 TreeLevel 조회하는 쿼리 메서드 추가
=> feat: 나뭇잎 지급 시 TreeLevel 자동 갱신 로직 추가

src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/publisher/AiVerificationPublisher.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/publisher/AwsAiVerificationSqsPublisher.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/publisher/GcpAiVerificationPubSubPublisher.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/subscriber/AwsVerificationResultDlqMessageSubscriber.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/subscriber/AwsVerificationResultSubscriber.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/subscriber/GcpVerificationResultDlqMessageSubscriber.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/subscriber/GcpVerificationResultSubscriber.java, src/main/resources/application-eks.yml
기존 GCP Pub/Sub 기반 인증 처리 로직을 AWS SQS 기반으로 이관하였습니다.  
프로덕션(GCP)과 개발(EKS/AWS) 환경을 명확히 분리하고, 메시지 전송 및 수신 처리를 모두 지원하도록 구성하였습니다.
- `application-eks.yml`: SQS 관련 큐 URL 추가
- `AiVerificationPublisher`: 인증 메시지 발행 인터페이스 정의
- `AwsAiVerificationSqsPublisher`: 인증 요청을 SQS에 전송 (재시도 포함)
- `AwsVerificationResultSubscriber`: 인증 결과 수신 및 처리
- `AwsVerificationResultDlqMessageSubscriber`: DLQ 수신 및 실패 로깅
- GCP 관련 Publisher/Subscriber에 `@Profile("!eks")` 설정
- AWS 관련 클래스에 `@Profile("eks")` 설정
=> feat: AWS SQS 기반 인증 요청 및 결과 처리 구현 및 GCP 분기 처리

src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/publisher/AiFeedbackPublisher.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/publisher/AwsAiFeedbackSqsPublisher.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/publisher/GcpAiFeedbackPubSubPublisher.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/subscriber/AwsAiFeedbackResultDlqSubscriber.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/subscriber/AwsAiFeedbackResultSubscriber.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/subscriber/GcpAiFeedbackResultDlqSubscriber.java, src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/subscriber/GcpAiFeedbackResultSubscriber.java, src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/publisher/AwsAiVerificationSqsPublisher.java
- 기존 GCP Pub/Sub 기반 피드백 결과 수신 로직과 동작을 동일하게 유지하면서 AWS SQS 환경에서 작동하는 클래스를 추가 구현하였습니다.
- eks 프로파일 여부에 따라 GCP와 AWS의 subscriber가 분기되어 동작하도록 구성했습니다.
- DLQ 처리, 피드백 발행 로직도 SQS용으로 분리하여 유연한 클라우드 전환 또는 멀티 클라우드 대응이 가능하게 하였습니다.
- AwsAiFeedbackResultSubscriber: SQS 기반 피드백 결과 메시지 처리 로직 구현
- AwsAiFeedbackResultDlqSubscriber: SQS 기반 DLQ 메시지 처리 구현
- AwsAiFeedbackSqsPublisher: 피드백 요청 SQS 발행 로직 구현
- AiFeedbackPublisher: 인터페이스 역할 수행
=> feat: 피드백 결과 발행/수신 기능을 AWS SQS 기반 구현 및 Profile 분리

src/main/java/ktb/leafresh/backend/domain/member/application/service/BadgeReadService.java, src/main/resources/application-docker-local.yml, src/main/resources/application-docker-prod.yml, src/main/resources/application-eks.yml, src/main/resources/application-local.yml
환경(dev, prod)에 따라 lock-image-url을 외부 설정값으로 주입할 수 있도록 분리 설정하였습니다.  
또한, 기존 BadgeReadService에서 사용하던 @Value 키 `${gcp.storage.lock-image-url}`을 `${lock-image-url}`로 통일하여  
환경 프로파일에 따라 일관되게 주입되도록 수정하였습니다.
- `application-local.yml`, `application-docker-local.yml`, `application-docker-prod.yml`, `application-eks.yml`에서
- `gcp.storage.lock-image-url: ${LOCK_IMAGE_URL}` → `lock-image-url: ${LOCK_IMAGE_URL}` 위치 변경
- `BadgeReadService.java`
- `@Value("${gcp.storage.lock-image-url}")` → `@Value("${lock-image-url}")`로 수정하여 키 통일
- 환경에 따라 서로 다른 `lockImageUrl` 주입 가능 (ex. dev는 S3, prod는 GCS)
- 잘못된 프로퍼티 경로로 인한 주입 실패 방지
- 유지보수 및 설정 관리 간결화
=> refactor: 환경별 lock-image-url 설정 분리 및 @Value 키 통일

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeDetailReadService.java, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeParticipantRecordRepository.java
기존에는 인증(Verification)이 존재하는 경우에만 참여한 것으로 간주되어,
참여하기 버튼만 누르고 인증하지 않은 경우에도 NOT_PARTICIPATED로 표시되는 문제가 있었습니다.
이를 해결하기 위해 resolveChallengeStatus() 메서드 내 로직을
ParticipantRecord 존재 여부로 판단하도록 수정하였습니다.
=> fix: 단체 챌린지 상세 조회 시 참여 상태 판단 기준을 인증 여부 → 참가 기록 여부로 수정

Dockerfile, src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeCreatedQueryRepositoryImpl.java
- Dockerfile: 테스트 건너뛰기 옵션(-x test) 추가로 빌드 실패 방지
- GroupChallengeCreatedQueryRepositoryImpl: fetch join 추가로 LazyLoading 문제 해결
- GroupChallengeCreatedQueryRepositoryImplTest의 "엔티티 필드 조회" 테스트 실패 수정
- 465개 테스트 중 1개 실패로 인한 전체 빌드 중단 문제 해결
=> fix: Docker 빌드 실패 및 테스트 오류 해결
