src/main/java/ktb/leafresh/backend/domain/challenge/group/application/factory/GroupChallengeExampleImageAssembler.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/application/factory/GroupChallengeFactory.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCreateService.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/AiChallengePolicyValidator.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/application/validator/GroupChallengeDomainValidator.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallenge.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/domain/entity/GroupChallengeExampleImage.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/client/AiChallengeValidationClient.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/client/FakeAiChallengeValidationClient.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/client/HttpAiChallengeValidationClient.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/dto/AiChallengeValidationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/dto/AiChallengeValidationResponseDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeCategoryRepository.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeRepository.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/controller/GroupChallengeController.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeCreateRequestDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/response/GroupChallengeCreateResponseDto.java
src/main/java/ktb/leafresh/backend/global/config/WebClientConfig.java
src/main/java/ktb/leafresh/backend/global/exception/ErrorCode.java
src/main/java/ktb/leafresh/backend/global/exception/GlobalExceptionHandler.java
src/main/java/ktb/leafresh/backend/global/init/GroupChallengeCategoryInitializer.java
src/main/java/ktb/leafresh/backend/global/response/ApiResponse.java
src/main/java/ktb/leafresh/backend/global/security/CustomUserDetails.java
src/main/java/ktb/leafresh/backend/global/security/CustomUserDetailsService.java
src/main/java/ktb/leafresh/backend/global/security/JwtFilter.java
src/main/java/ktb/leafresh/backend/global/security/TokenProvider.java
src/main/resources/application.yml

- 단체 챌린지 생성 기능 구현
- `/api/challenges/group` POST 엔드포인트 생성
- 챌린지 정보, 예시 이미지 리스트, 카테고리 등을 포함한 등록 요청 처리
- `GroupChallengeCreateService` 작성
- 도메인 유효성 검증 및 AI 예시 이미지 정책 검증 로직 포함
- 챌린지 및 관련 엔티티(예시 이미지 등) 저장
- `GroupChallengeFactory`, `GroupChallengeExampleImageAssembler` 작성
- 복합 엔티티 조립 및 생성 책임 분리
- `GroupChallengeDomainValidator`, `AiChallengePolicyValidator` 구현
- 제목, 설명, 인증 시간 등 도메인 정책 검증
- 예시 이미지 수, 성공/실패 조건 유효성 검증
- AI 인증 정책 검증 클라이언트 구성
- `AiChallengeValidationClient` 인터페이스 정의
- `HttpAiChallengeValidationClient`, `FakeAiChallengeValidationClient` 구현
- `WebClientConfig` 설정 추가 및 application.yml에 base-url 등록
- 보안 설정 수정
- `JwtFilter`, `TokenProvider`, `CustomUserDetailsService` 수정
- 토큰 내 PK(memberId)를 기반으로 DB 조회하여 인증 처리
- 응답 포맷 통일
- `ApiResponse`, `ApiResponseConstants` 기반 응답 래핑 적용
---
- 예시 이미지 …

feat: 단체 챌린지 생성 기능 구현

---

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveService.java
src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationSubmitService.java
src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveService.java
src/main/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationSubmitService.java
src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/GroupChallengeVerification.java
src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/PersonalChallengeVerification.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/AiGroupChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/AiPersonalChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/FakeAiGroupChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/FakeAiPersonalChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/HttpAiGroupChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/client/HttpAiPersonalChallengeVerificationClient.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/dto/request/AiGroupChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/verification/infrastructure/dto/request/AiPersonalChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/GroupChallengeVerificationController.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/PersonalChallengeVerificationController.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/controller/VerificationResultController.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/GroupChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/PersonalChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/VerificationResultRequestDto.java
src/main/java/ktb/leafresh/backend/global/common/entity/enums/ChallengeType.java
src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
src/main/java/ktb/leafresh/backend/global/exception/ChallengeErrorCode.java
src/main/java/ktb/leafresh/backend/global/exception/VerificationErrorCode.java

1. 개인/단체 챌린지 인증 제출 기능 구현
- 사용자가 이미지 및 텍스트 인증을 제출하면, 하루 1회 제한 조건을 검사한 뒤 DB에 저장
- 인증 상태는 `PENDING_APPROVAL`로 저장되며, 이후 AI 판정 결과에 따라 상태 변경
2. AI 서버 요청 기능
- 인증 제출 시 AI 서버로 이미지 URL, 사용자 및 챌린지 정보를 포함한 요청 전송
- 실제 HTTP 통신용 Client와 테스트용 Fake Client를 분리하여 구현
3. 인증 결과 수신 및 상태 반영
- AI 서버에서 전송하는 인증 결과를 수신하는 콜백 API(`/api/verification/result`)를 구현
- 결과(승인/거절)에 따라 인증 상태를 업데이트
- 인증 제출 시 AI 서버 요청 전송 확인
- 하루 1회 인증 제한 로직 정상 동작 확인
- 인증 결과 수신 API를 통해 상태 업데이트 정상 반영 확인
- `SecurityConfig`에 결과 수신 API 인증 제외 설정 포함
- 각 도메인 별로 요청 DTO, 엔티티, 서비스, 컨트롤러 구조를 일관되게 구성

feat: 개인/단체 챌린지 인증 제출 및 AI 연동 기능 구현

---

.gitignore
build.gradle
src/main/java/ktb/leafresh/backend/domain/auth/presentation/dto/request/OAuthSignupRequestDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeCreateRequestDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/presentation/dto/request/GroupChallengeUpdateRequestDto.java
src/main/java/ktb/leafresh/backend/domain/challenge/personal/presentation/dto/request/PersonalChallengeCreateRequestDto.java
src/main/java/ktb/leafresh/backend/domain/image/application/service/GcsService.java
src/main/java/ktb/leafresh/backend/domain/image/presentation/controller/GcsController.java
src/main/java/ktb/leafresh/backend/domain/image/presentation/dto/request/PresignedUrlRequestDto.java
src/main/java/ktb/leafresh/backend/domain/image/presentation/dto/response/PresignedUrlResponseDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/GroupChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/request/PersonalChallengeVerificationRequestDto.java
src/main/java/ktb/leafresh/backend/global/config/GcsConfig.java
src/main/java/ktb/leafresh/backend/global/validator/GcsImageUrlValidator.java
src/main/java/ktb/leafresh/backend/global/validator/ValidGcsImageUrl.java

Google Cloud Storage(GCS)와 연동하여 Presigned URL을 발급하고, 해당 URL의 유효성을 검증하는 기능을 추가하였습니다.
- gcs.json 키 파일 추가 및 의존성 등록
- GCS 관련 설정 추가
- Presigned URL 발급 API 추가
- URL 발급 메서드 및 서비스 로직 구현
- 발급된 URL의 유효성 검사 기능 추가
- Presigned URL 요청/응답용 DTO 클래스 작성

feat: GCS Presigned URL 발급 및 유효성 검증 기능 추가

---

src/main/java/ktb/leafresh/backend/global/security/AuthCookieProvider.java
src/main/resources/application-bigbang.yml
src/main/resources/application-local.yml
src/main/resources/application.yml

- `server.forward-headers-strategy: framework` 설정 추가  
→ 프록시(Nginx 등) 환경에서 `X-Forwarded-*` 헤더 처리 가능
- 쿠키 설정 개선
- `cookie.secure`, `cookie.samesite` 값을 yml에서 주입받도록 수정
- 운영환경에서는 `SameSite=None`, 로컬에서는 `Lax` 설정
- `AuthCookieProvider`에서 하드코딩된 `SameSite` 제거 후 설정값 주입 방식으로 변경
- 환경별 설정 분리 및 유지보수성 향상
- 인증 쿠키 전달 오류 해결 (`SameSite`, `Secure` 대응)

feat: 쿠키 정책 설정을 위한 application.yml 환경 구성 개선

---

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationService.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotBaseInfoClient.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/client/HttpAiChatbotFreeTextClient.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/response/AiChatbotBaseInfoApiResponseDto.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/response/AiChatbotFreeTextApiResponseDto.java

- AI 챗봇 관련
- `AiChatbotBaseInfoApiResponseDto`, `AiChatbotFreeTextApiResponseDto` 응답 DTO 신규 생성
- 클라이언트 요청 및 응답 단계에 로그 추가 (HttpAiChatbot*Client.java)
- 챗봇 추천 NPE 방지
- `ChatbotRecommendationService`에서 Optional 처리로 NullPointerException 방지
- AI 챗봇 응답 처리와 클라이언트 로그 가시성 향상

feat: AI 응답 DTO 추가 및 예외 처리 개선

---

src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeCategoryService.java
src/main/java/ktb/leafresh/backend/domain/challenge/group/application/service/GroupChallengeDetailReadService.java

- API별 발생 가능한 예외 상황을 ErrorCode Enum으로 상수화
- Controller 및 Service에서 직접 문자열이 아닌 ErrorCode를 통해 예외 처리
- 중복된 에러 메시지 제거 및 예외 처리 일관성 확보
- 전역 CustomException 및 GlobalErrorCode, 도메인별 ErrorCode 구조 정리

refactor: 에러 코드 상수화 및 예외 처리 로직 통합 리팩토링

---

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationService.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotBaseInfoRequestDto.java
src/main/java/ktb/leafresh/backend/domain/chatbot/infrastructure/dto/request/AiChatbotFreeTextRequestDto.java
src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/controller/ChatbotRecommendationController.java
src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/request/ChatbotBaseInfoRequestDto.java
src/main/java/ktb/leafresh/backend/domain/chatbot/presentation/dto/request/ChatbotFreeTextRequestDto.java

- FE 요청 바디에 conversationId 필드 반영
- AI 요청 바디에도 conversationId 포함
- 관련 DTO 및 서비스/컨트롤러 전체 수정
- System.out.println → log로 리팩토링

feat: 챗봇 추천 요청에 conversationId 필드 추가

---

src/main/java/ktb/leafresh/backend/domain/member/domain/entity/enums/BadgeType.java
src/main/java/ktb/leafresh/backend/domain/member/infrastructure/repository/BadgeRepository.java
src/main/java/ktb/leafresh/backend/global/initializer/BadgeInitializer.java

- BadgeInitializer.java 추가: GROUP, PERSONAL, TOTAL, SPECIAL, EVENT 뱃지 초기화 구현
- BadgeRepository.java 생성: 이름 기반 중복 방지용 메서드(findByName) 정의
- BadgeType enum에 각 뱃지 타입 주석 추가
- 추후 사용자 뱃지 지급 로직과 연결 예정

feat: BadgeInitializer 구현 및 BadgeType 주석 추가

---

src/main/java/ktb/leafresh/backend/domain/feedback/application/service/FeedbackReadService.java

사용자가 피드백 페이지에 진입했을 때 수행되는 일반 조회에서도 Redis 캐시를 우선 조회하도록 개선했습니다.
- `FeedbackReadService#getFeedbackForLastWeek()`에서 Redis 캐시 우선 조회
- 캐시 미스 시 DB fallback 및 null 처리
- 조회 캐시 히트/미스 로깅 추가

feat: 일반 피드백 조회 시 Redis 캐시 활용

---

src/main/java/ktb/leafresh/backend/domain/store/product/domain/entity/Product.java
src/main/java/ktb/leafresh/backend/domain/store/product/domain/factory/ProductFactory.java
src/main/java/ktb/leafresh/backend/domain/store/product/presentation/dto/request/ProductUpdateRequestDto.java
src/main/java/ktb/leafresh/backend/global/config/RedisConfig.java
src/main/java/ktb/leafresh/backend/global/exception/ProductErrorCode.java

- 일반 상품 수정 기능 구현을 위한 요청 DTO, 팩토리 클래스, 에러 코드 등을 추가하고,
- RedisTemplate의 직렬화 설정을 개선하여 객체 저장 안정성을 확보하였습니다.
- 일반 상품 수정 요청 DTO (`ProductUpdateRequestDto`) 추가
- `ProductCreateRequestDto` → `Product` 생성 팩토리 클래스 (`ProductFactory`) 추가
- Product 도메인 관련 에러 코드 Enum 정의 및 적용
- RedisTemplate 설정 개선
- `GenericJackson2JsonRedisSerializer` 사용
- `JavaTimeModule` 등록된 `ObjectMapper` 적용
- `hashKeySerializer`, `hashValueSerializer` 명시 설정

feat: 일반 상품 수정 관련 기능 추가  및 Redis 설정 개선

---

src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentCreateService.java
src/main/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentUpdateService.java
src/main/java/ktb/leafresh/backend/domain/verification/domain/entity/Comment.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/assembler/CommentHierarchyBuilder.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/response/CommentListResponseDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/response/CommentSummaryResponseDto.java
src/main/java/ktb/leafresh/backend/domain/verification/presentation/dto/response/CommentUpdateResponseDto.java
src/main/java/ktb/leafresh/backend/global/common/entity/BaseEntity.java
src/main/java/ktb/leafresh/backend/global/config/SecurityConfig.java
src/main/java/ktb/leafresh/backend/global/exception/VerificationErrorCode.java

댓글 기능 개선을 위한 전체적인 구조 개편 및 기능 추가 작업을 수행하였습니다. 댓글 수정, 대댓글 작성, 댓글 트리 응답 구조 도입 등을 포함하며, 이에 따라 인증 피드 관련 API 보안 설정도 일부 수정했습니다.
- BaseEntity에 soft delete 복구용 `restore()` 메서드 추가
- 댓글 수정 기능 개발
- 도메인 메서드 추가
- 응답 DTO 및 서비스 로직 구현
- 댓글 트리 구조 대응
- `CommentHierarchyBuilder` 유틸 클래스 추가
- `CommentSummaryResponseDto`, `CommentListResponseDto` 정의
- 댓글/대댓글 작성 서비스 로직 구현 및 예외 처리 추가
- `GET /api/challenges/group/{challengeId}/verifications/{verificationId}` 경로는 인증 없이 접근 가능하도록 Security 설정 수정

feat: 댓글 CRUD 및 트리 응답 구조 도입

---

src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationFeedServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultQueryServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationResultSaveServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupChallengeVerificationSubmitServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentCreateServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentDeleteServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentQueryServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationCommentUpdateServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/GroupVerificationLikeServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultQueryServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationResultSaveServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/PersonalChallengeVerificationSubmitServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountQueryServiceTest.java
src/test/java/ktb/leafresh/backend/domain/verification/application/service/VerificationCountReadServiceTest.java
src/test/java/ktb/leafresh/backend/support/fixture/GroupChallengeVerificationFixture.java

- 인증 관련 서비스 로직에 대한 단위 테스트 작성
- 인증 및 인증 커뮤니티 관련 테스트
- 필요한 도메인 객체 픽스처 추가

test: 인증 도메인 유닛 테스트 및 픽스처 구성

---

src/test/java/ktb/leafresh/backend/domain/store/product/application/service/ProductCreateServiceTest.java
src/test/java/ktb/leafresh/backend/domain/store/product/application/service/ProductSearchReadServiceTest.java
src/test/java/ktb/leafresh/backend/domain/store/product/application/service/ProductUpdateServiceTest.java
src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealCreateServiceTest.java
src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealProductReadServiceTest.java
src/test/java/ktb/leafresh/backend/domain/store/product/application/service/TimedealUpdateServiceTest.java
src/test/java/ktb/leafresh/backend/support/fixture/ProductFixture.java
src/test/java/ktb/leafresh/backend/support/fixture/TimedealPolicyFixture.java

- 상품 도메인 로직에 대한 단위 테스트 추가
- 일반 상품, 타임딜 정책 관련 테스트 작성
- ProductFixture, TimedealPolicyFixture 도입 및 mock 객체 구성

test: 상품 도메인 유닛 테스트 및 픽스처 추가

---

src/main/java/ktb/leafresh/backend/domain/chatbot/application/service/ChatbotRecommendationSseService.java

- UriComponentsBuilder.encode() 적용으로 한글 및 공백 파라미터 400 오류 관련 작업
- 파라미터 및 최종 URI 로깅으로 문제 추적 가능하도록 개선

fix: AI SSE 요청 URI 인코딩 문제 해결 및 디버깅 로그 추가

---

.github/workflows/be-cicd.yml
.github/workflows/discord-notification.yml

Deploy 통과 시 / PR 생성 시 디스코드 알림 전송 기능 구현 완료

CI/CD 파일 변경 및 PR 알림코드 추가

---

src/main/java/ktb/leafresh/backend/domain/chatbot/application/handler/ChatbotSseStreamHandlerImpl.java

- SSE 이벤트 수신 시 eventName 또는 data가 null/blank일 경우에 대한 예외 처리 로직을 추가했습니다.
- event.data()가 빈 문자열일 경우 `emitter.send(comment("ping"))` 형태로 keep-alive 처리를 합니다.
- "close" 이벤트 수신 시 명시적으로 `emitter.complete()` 호출하여 SSE 연결을 종료합니다.
- SSE 전송 중 IOException 발생 시 `completeWithError()` 호출로 안정적 종료 처리.
- 프론트에서 `event: null` 이 발생하지 않도록 사전 방지
- 빈 이벤트 수신 시 클라이언트 오류/재연결 발생 가능성 방지
- 정상 흐름 외 종료 또는 예외 상황에 대한 명확한 처리 보장
- 실제 SSE 응답에서 event가 null이거나 빈 경우, 서버 로그에 경고 로그만 찍히고 전송되지 않음
- 정상 데이터 수신 시 `.name().data()`로 전달되고, 빈 데이터는 `ping`으로 대체됨
- `"close"` 이벤트 수신 시 `emitter.complete()` 호출로 스트림 종료 확인 가능
- 프론트에서 `event: null` 로그 발생 문제
- 클라이언트의 예기치 않은 재연결 현상 대응

fix: SSE 이벤트 수신 시 null/빈값 처리 및 안정성 개선

---

src/main/java/ktb/leafresh/backend/domain/feedback/infrastructure/client/HttpFeedbackCreationClient.java

AI 서버가 피드백 요청을 정상 수신했으나 비동기 처리 방식으로 `202 Accepted` 응답을 반환할 때,
기존 로직에서는 `data.content == null`을 이유로 예외를 발생시키는 문제가 있었습니다.
이번 수정에서는 status == 202일 경우 `data`가 없어도 정상 흐름으로 인정하도록 수정했습니다.
- `HttpFeedbackCreationClient` 내부 로직을 status 기준 분기 처리
- 200 OK → content 필수
- 202 Accepted → content 없어도 정상 처리
- 그 외 status → 예외 처리
- 관련 로그 메시지 구분 처리
- 이후 콜백 기반으로 결과 수신 시점에만 content 유효성 체크 필요

feat: AI 피드백 응답 status 202 처리 허용 및 예외 제거

---

docker-compose-be.yml

GOOGLE_APPLICATION_CREDENTIALS 경로를 기존의 leafresh-gcs.json → leafresh-dev2.json

작업: docker-compose-be.yml을 인프라 레포 내용으로 수정

---

.github/workflows/be-cicd.yml
Dockerfile

feat : signoz 도입

---

.github/workflows/be-cicd.yml

GSM 업로드 시 생성되는 값 이름 변경
- .이나 - 같은 문자들이 입력이 되지 않아 언더바 (_)로 변경

Update: GSM 업로드 시 생성되는 값 이름 변경

---

.github/workflows/FECICE
.github/workflows/be-cicd.yml
helm/backend/.helmignore
helm/backend/Chart.yaml
helm/backend/templates/_helpers.tpl
helm/backend/templates/deployment.yaml
helm/backend/templates/hpa.yaml
helm/backend/templates/ingress.yaml
helm/backend/templates/secret.yaml
helm/backend/templates/service.yaml
helm/backend/templates/serviceaccount.yaml
helm/backend/values.yaml

- 백엔드(Spring Boot) 애플리케이션을 EKS에 배포하기 위해 DEV 환경용 Helm Chart 추가
- helm/backend/Chart.yaml 및 templates 추가
- values.yaml 작성 (DEV 환경 기본값 정의)
- .github/workflows/be-cicd.yml 일부 정리

feat: 백엔드(DEV) Helm Chart 추가

---

src/test/java/ktb/leafresh/backend/domain/member/application/service/MemberUpdateServiceTest.java

- updateMemberInfo() 메서드 파라미터 변경 반영 (Member -> Long memberId)
- memberRepository.findById() 모킹 추가
- 존재하지 않는 회원 ID 예외 처리 테스트 케이스 추가
- 모든 테스트 케이스에서 Member 조회 로직 모킹 적용
변경사항:
- 메서드 호출 시 Member 객체 대신 memberId 전달
- MEMBER_NOT_FOUND 예외 테스트 케이스 신규 추가
- 테스트 셋업에서 memberId 변수 분리

test: MemberUpdateService 메서드 시그니처 변경에 따른 테스트 수정

---

.github/workflows/be-cicd.yml
build.gradle
docs/TEST_INFRASTRUCTURE_ISSUES.md
gradle.properties
src/test/java/ktb/leafresh/backend/domain/challenge/group/infrastructure/repository/GroupChallengeVerificationQueryRepositoryImplTest.java
src/test/java/ktb/leafresh/backend/support/config/IntegrationTestSupport.java
src/test/java/ktb/leafresh/backend/support/config/RepositoryTestSupport.java
src/test/java/ktb/leafresh/backend/support/config/TestJpaConfig.java
src/test/resources/application-test.yml

주요 변경사항:
- Repository 계층 테스트 안정화를 위한 설정 추가
- 단위 테스트와 통합 테스트 분리 (unitTest, integrationTest 태스크)
- CI/CD에서 단위 테스트만 실행하도록 최적화 테스트 환경 설정 개선 및 메모리 최적화
추가된 파일:
- TestJpaConfig: JPA 테스트용 설정 클래스
- IntegrationTestSupport, RepositoryTestSupport: 테스트 지원 클래스
- TEST_INFRASTRUCTURE_ISSUES.md: 테스트 인프라 문제점 및 해결방안 문서
수정된 파일:
- build.gradle: 테스트 태스크 분리, CI 환경 최적화, 메모리 설정 추가
- .github/workflows/be-cicd.yml: 단위 테스트만 실행하도록 변경
- application-test.yml, gradle.properties: 테스트 환경 설정 개선

test: 테스트 인프라 안정화 및 CI/CD 최적화

---

.github/workflows/swagger-docs.yml
docs/DEPLOYMENT_GUIDE.md
docs/README.md
docs/_config.yml
docs/index.html
scripts/run-swagger.sh
scripts/test-swagger.sh

- Add GitHub Actions workflow for API docs generation
- Create responsive landing page in docs/index.html
- Add development scripts for local Swagger testing
- Configure GitHub Pages with Jekyll optimization
- Include comprehensive deployment documentation
Deployed at: https://100-hours-a-week.github.io/15-Leafresh-BE/

feat: Setup automated Swagger UI deployment to GitHub Pages
